ComparativeGenomicsToolkit/cactus

src/cactus/blast/blast.py
Deleting blast chunks in `CollateBlasts2` jobs after collating them seems to take a while 
```
for resultsFileID in self.resultsFileIDs:
fileStore.deleteGlobalFile(resultsFileID)
```
This PR parallelizes this loop into child(tree) jobs.
=> Delete blast chunks in parallel after collation

.gitlab-ci.yml, Makefile
This (or something similar) would be a great start to gitlab integration tests.  It currently runs in about 1.5 hours on my 8 core / 32G desktop.  I bet it would be similar on 4 cores / 8G.  About 32G disk should be fine.  If any toil folks @DailyDreaming @adamnovak @diekhans  would be able to hook this up, I'd be much obliged.
=> Get ready for gitlab

src/cactus/progressive/cactus_createMultiCactusProject.py, src/cactus/progressive/multiCactusProject.py, src/cactus/progressive/projectWrapper.py
This isn't urgent and only adds error checks, so may way until gitllab support is done.
issue identified in #103
=> detect when --root is a leaf node

src/cactus/progressive/cactus_progressive.py
When no `--binariesMode` option given, default to `local` if the binaries are detected.  This makes running from the new Dockerfile a little simpler.  
Also, give an error right away when trying to run single machine with 1 core.  
Resolves #183 (Jean's example runs through on 2 cores, so using that as the minimum)
=> Default to local binaries and error message for 1 core

.travis.yml, Dockerfile, Makefile, api/Makefile, bar/Makefile, blast/Makefile, blastLib/Makefile, caf/Makefile, check/Makefile, dbTest/Makefile, faces/Makefile, hal/Makefile, include.mk, normalisation/Makefile, phylogeny/Makefile, phylogeny/treelib/Makefile, pipeline/Makefile, preprocessor/Makefile, preprocessor/lastzRepeatMasking/Makefile, reference/Makefile, setup/Makefile
Allows option build of static executables with `make static`
fixed #190
as this includes a large number of minor changes to makefiles, it is suggested reviewing it buy building in different environments rather than inspection.
=> add make static target to build static executables

src/cactus/shared/common.py
=> Corrected unqualified references to subprocess members

DEVELOPMENT.md, src/cactus/blast/cactus_blast.py, src/cactus/preprocessor/cactus_preprocessor.py, src/cactus/progressive/cactus_prepare.py, src/cactus/progressive/cactus_progressive.py, src/cactus/setup/cactus_align.py, src/cactus/shared/common.py
add the ability for cactus python main programs to dump all thread stacks if sigusr1 is received
=> add ability for cactus python main programs to dump all thread stacks

.travis.yml, DEVELOPMENT.md
- updated to latest hal
- move cactusTestData to ComparativeGenomicsToolkit github project
=> Submodule update

src/cactus/blast/blast.py, src/cactus/cactus_progressive_config.xml, src/cactus/pipeline/cactus_workflow.py, src/cactus/progressive/cactus_prepare.py, src/cactus/shared/common.py
Small change to clean up the interface for testing gpu-based lastz.
=> Simplify gpu toggle

README.md, src/cactus/blast/cactus_blast.py, src/cactus/progressive/cactus_prepare.py, src/cactus/setup/cactus_align.py, test/evolverTest.py
* Simplify command line, so only input needed is the seqFile and only output is the WDL script.
* Support configFile inputs as optional input parameters in WDL tasks/workflows
* More options for resource tuning
* First crack at instructions for running on Terra in the README
=> Improve WDL interface

.gitlab-ci.yml
This hack is an attempt to resolve #224 by giving it multiple tries to apt-install kyoto cabinet.
=> Try installing kyoto cabinet more than once in gitlab setup

src/cactus/progressive/cactus_prepare.py
=> fix bug in wdl where local input files were garbled

Makefile, test/evolverTest.py
with special make target
fixes #256
should not merge until we figure out how to make CI tests faster (# 253)
=> added version of tests that run full cactus in local mode

test/evolverTest.py
Couldn't find an option to make cromwell stop doing this, so adding a command in the teardown to remove them from docker. 
Will hopefully resolve #255
=> Remove root-owned temp files created by cromwell in evolver-test

bar/impl/flowerAligner.c, blast/cactus_blast_chunkFlowerSequences.c, blast/cactus_blast_chunkSequences.c, blast/cactus_coverage.c, blastLib/blastAlignmentLib.c, blastLib/blastAlignmentLib.h, preprocessor/cactus_analyseAssembly.c, preprocessor/cactus_batch_mergeChunks.c, setup/cactus_setup.c
Merge https://github.com/benedictpaten/sonLib in order to get recent changes by @tpesout that help with multithreading.
=> Merge in latest sonlib from upstream

README.md, src/cactus/blast/blast.py, src/cactus/progressive/cactus_prepare.py
This fixes a bug I found when running at scale. 
Would also like to
* try using `taskset` to keep `run_wga_gpu` from using more cores than the toil job that calls it has.
* investigate the realign jobs.  I'm worried that not splitting up the faasta for lastz may be causing them to get too big.  May need option to parallelize them separately.
=> GPU interface tweaks

.gitlab-ci.yml, Dockerfile, Dockerfile.ci-base, Makefile, src/cactus/pipeline/cactus_workflow.py, src/cactus/progressive/cactus_prepare.py, src/cactus/shared/common.py
In particular, turn off realignment when using the gpu and call gpu lastz by its new name.
=> Minor cactus-prepare fixes

src/cactus/progressive/cactus_prepare.py
This fixes cactus-prepare to handle chains of virtual dependencies -- any past the first were missing before.
Resolves #277
=> Fix scheduling bug in cactus-prepare

.travis.yml, Makefile, build-tools/makeBinRelease
=> Update cPecan to one that preserves cflags in lastz

Dockerfile, build-tools/makeBinRelease, build-tools/makeGpuDockerRelease
These are mistakes I've caught when testing v1.1.0.  Speaking of mistakes, this was erroneously committed (now reverted) to master.
=> Release process fixes

src/cactus/progressive/cactus_prepare.py
@thiagogenez found a bug in `cactus-prepare` where it would fail to schedule a large tree.  This is because it wasn't handling chains of "virtual" dependencies.  This is corrected in this PR
=> fix prepare schedule bug

.gitmodules, Dockerfile, Makefile, bar/Makefile, bar/cactus_bar.c, bar/impl/endAligner.c, bar/impl/flowerAligner.c, bar/impl/poaAligner.c, bar/inc/endAligner.h, bar/inc/flowerAligner.h, bar/inc/poaAligner.h, bar/tests/endAlignerTest.c, bar/tests/flowerAlignerTest.c, bar/tests/runEndAlignment.c, build-tools/makeBinRelease, include.mk, src/cactus/cactus_progressive_config.xml, src/cactus/pipeline/cactus_workflow.py, src/cactus/shared/common.py, test/evolverMammals-default.comp.xml, test/evolverPrimates-default.comp.xml, test/evolverTest.py
This is just #328 but with the commit history cleaned up a bit.
=> Poa rebase

src/cactus/progressive/cactus_prepare.py
=> add --containerImage option to cactus-prepare-toil

.gitlab-ci.yml, Dockerfile, README.md, ReleaseNotes.md, bar/cactus_bar.c, bar/impl/poaBarAligner.c, bar/inc/poaBarAligner.h, bar/tests/poaBarTest.c, bar/tests/runEndAlignment.c, build-tools/downloadMiniTools, build-tools/downloadPangenomeTools, build-tools/makeBinRelease, src/cactus/cactus_progressive_config.xml, src/cactus/pipeline/cactus_workflow.py, src/cactus/refmap/cactus_graphmap.py, src/cactus/setup/cactus_align.py, src/cactus/shared/common.py
Also, some minigraph pipeline tweaks.
=> Expose POA banding parameters

bar/impl/poaBarAligner.c, bar/tests/allTests.c
Hey @glennhickey , please try this out to see if it fixes the overlap crash issue.
=> Small fixes to overlap of masked sequences, also fixing bar tests.

Dockerfile, build-tools/downloadPangenomeTools, build-tools/makeBinRelease, src/cactus/cactus_progressive_config.xml, src/cactus/setup/cactus_align.py, test/evolverTest.py
* fix up some `cactus-align` bugs that crept int
* fix architecture flags in various build steps (changing back to nehalem)
* other stuff (in progress)
=> Further pangenome cleanup

src/cactus/cactus_progressive_config.xml, src/cactus/preprocessor/cactus_preprocessor.py, src/cactus/preprocessor/dnabrnnMasking.py, src/cactus/shared/common.py
that came up when testing at scale.
=> Fix bugs in PAF repeatmasker

bar/impl/poaBarAligner.c, src/cactus/cactus_progressive_config.xml, src/cactus/setup/cactus_align.py
The new abPOA didn't let me drop the windowing logic like I thought when aligning 90 genomes.  Or even increase the window size for that matter.  So this PR reverts back to using the stitching with 10kb window size like before.   Maybe playing with the seeding parameters can eventually help a bit.
=> Re-activate stitching

bar/impl/poaBarAligner.c, src/cactus/cactus_progressive_config.xml
Not sure if it does anything yet
=> add config option for abpoa --progressive

src/cactus/setup/cactus_align.py
Hoping this will fix the crashes I'm seeing when building pangenomes with the current master.
=> Fix --pangenome overrides to use updated config XML

bar/impl/poaBarAligner.c
This probably makes no difference, but am still trying to figure out a weirdo POA segfault that doesn't reproduce on command line.
=> Don't re-use poa graph

README.md, ReleaseNotes.md, build-tools/makeGpuDockerRelease, doc/pangenome.md, src/cactus/blast/blast.py, src/cactus/blast/cactus_blast.py, src/cactus/cactus_progressive_config.xml, src/cactus/pipeline/cactus_workflow.py, src/cactus/preprocessor/cactus_preprocessor.py, src/cactus/progressive/cactus_prepare.py, src/cactus/progressive/cactus_progressive.py, src/cactus/progressive/multiCactusProject.py, src/cactus/refmap/cactus_graphmap.py, src/cactus/refmap/cactus_graphmap_join.py, src/cactus/refmap/cactus_graphmap_split.py, src/cactus/refmap/paf_to_lastz.py, src/cactus/setup/cactus_align.py, src/cactus/shared/common.py
I think it's about time to cut a release, even if there are a few known issues.  Still, I'd like to at least take a look at what seems a major CAF speed regression (due to parameters?) on the mouse/rat node of the 12-way test.
=> WIP: Prep next release

ReleaseNotes.md, src/cactus/progressive/cactus_progressive.py, src/cactus/setup/cactus_align.py
Resolves #519 
Thanks @RenzoTale88
=> Fix --consCores / --maxCores check

build-tools/downloadPangenomeTools
(was temporarily using hand-built one in order to get at features that weren't in 1.33.0)
=> Switch to official vg release (1.34.0)

Makefile, build-tools/downloadPangenomeTools, paf/impl/paf.c, src/cactus/blast/__init__.py, src/cactus/blast/cactus_blast.py, src/cactus/cactus_progressive_config.xml, src/cactus/paf/local_alignment.py, src/cactus/pipeline/cactus_workflow.py, src/cactus/preprocessor/cactus_preprocessor.py, src/cactus/preprocessor/checkUniqueHeaders.py, src/cactus/progressive/cactus_prepare.py, src/cactus/progressive/cactus_progressive.py, src/cactus/refmap/cactus_graphmap.py, src/cactus/refmap/cactus_refmap.py, src/cactus/setup/cactus_align.py, test/evolverTest.py
I've made a rule for every pytest in `test/evolverTest.py` in the Makefile.  So they can all be run as usual with `make evolver_test`, or run one at a time.  All tests that do not require Docker to be installed can be run at once with `make evolver_test_all_local`
@benedictpaten I'll take some time now to get some of these tests passing, including working on the preprocessor.
=> add make rule for every test, and one for all local tests

src/cactus/paf/local_alignment.py
`cactus_call` usually detects paths in parameters and automatically sends something sensible to `docker run` with an appropriate `-v`, but it doesn't seem to work with `lastz`.  So set the work_dir by hand....
=> specify lastz command workdir to help cactus_call set docker mount

bar/impl/poaBarAligner.c
This fixes one issue I ran into
=> Small fix to adapt to recent abpoa api change

build-tools/downloadPangenomeTools
=> Switch to latest release of hal2vg

api/impl/cactus_params_parser.c, build-tools/downloadPangenomeTools, include.mk, src/cactus/progressive/cactus_prepare.py, src/cactus/progressive/progressive_decomposition.py, src/cactus/progressive/seqFile.py, src/cactus/refmap/cactus_graphmap.py, src/cactus/setup/cactus_align.py
will need to talk to Heng about minigraph, as it doesn't seem to have arm support yet (should be fairly trivial to use the same framework as minimap2)
=> arm support for minimap2 build

Dockerfile, setup.py
It's a pretty heavy dependency and doesn't seem used anywhere. @diekhans any reason you can think of not to do this?
=> Remove cython

blast/cactus_coverage.c
by default `cactus_call` sets stderr to `subprocess.PIPE` when running popen.  Then it reads it with `communicate()`.  The upshot of this is that if there's tons of data in stderr, it gets read into memory.  Like from `cacuts_coverage` which can write a warning line *per base* if it gets more that 16bytes of coverage.  I think this is behind #681 where just calling `cactus_coverage` is taking 100's of gigs.  
`cactus_call` should be hardened to avoid this, but I don't want to change it before the next big merge.  This PR just fixes the main culprit, `cactus_coverage` to cap its warnings at 100.  
resolves #681
=> stop spamming stderr with warnings in cactus_coverage

Makefile, test/evolverTest.py
This test adds a couple primates to the evolverMammals hal and makes sure the results are sane.  One is added with cactus-blast/align and the other with just cactus.  
Resolves #685
=> Add test for add-to-node functionality

Dockerfile
I remember reading a blog about making slim docker images via two-stage builds, and a lot of what was in the cactus Dockerfile, like passing wheels and calling apt remove, came from that.  And... it turns out it was all nonsense. I'd never thought something on the internet could be so misleading but here we are...
Anyway, this PR tries to clean things up a bit.  All building is moved to the first stage, and the second stage only copies stuff over directly to where it needs to go.   
resolves #692
=> remove bunch of bloat from docker build

Makefile, test/evolverTest.py
Spoiler:  like adding to a node(#685), it doesn't work.
=> Quick add-to-branch test

Makefile
=> Dont copy lastz src files into bin/

src/cactus/progressive/cactus_prepare.py
The `--gpu` option in `cactus-prepare` predates GPU preprocessing and was never modified to incorporate it..  This PR changes `cactus-prepare --gpu` to not bother setting up a config and rather just tack `--gpu` to all appropriate commands. 
Of course, due to #678, this won't work as desired until paf_chains gets merged into master.  So in the meantime, anyone using the GPU outside the gpu docker release needs to manually edit their config
```
sed -i -e src/cactus/cactus_progressive_config.xml -e 's/gpuLastz="false"/gpuLastz="true"/g' 
pip install -U .
```
(or edit a copy of the config and pass it in via `--configFile`)
=> Fix up cactus-prepare --gpu

Dockerfile
=> update HAL in order to fix UDC support

Dockerfile
It seems to be working today.  Will just leave it in, but remove the test (which has the potential to download 200G if/when the cache doesn't feel like working as it did yesterday).  Resolves #712
=> Re-enable UDC in dockerfile

paf/Makefile, paf/fasta_extract.c, paf/impl/paf.c, paf/inc/paf.h, paf/paf_dechunk.c, paf/paf_tile.c, paf/paf_to_bed.c, paf/paf_upconvert.c, paf/tests/allTests.c, paf/tests/fasta_extract_test.c, paf/todo.txt, src/cactus/cactus_progressive_config.xml, src/cactus/paf/local_alignment.py, src/cactus/pipeline/cactus_workflow.py, src/cactus/progressive/cactus_progressive.py
=> Paf chains outgroup trim

src/cactus/paf/local_alignment.py
Not sure how this one made it this far: when doing outgroup alignments the distance was hardcoded to "1", leading to the slowest possible lastz parameters getting used : `--step=1 --ambiguous=iupac,100,100 --ydrop=3000`.
This PR changes it to use the same distance matrix as used for ingroups.
=> Fix lastz parameters bug for outgroups

src/cactus/progressive/cactus_progressive.py, src/cactus/progressive/progressive_decomposition.py
Also, fix `--skipPreprocessor` option.
Resolves #784
=> Error message for invalid --root

src/cactus/blast/cactus_blast.py, src/cactus/preprocessor/cactus_preprocessor.py, src/cactus/progressive/cactus_progressive.py, src/cactus/refmap/cactus_graphmap.py, src/cactus/refmap/cactus_graphmap_join.py, src/cactus/refmap/cactus_graphmap_split.py, src/cactus/refmap/cactus_minigraph.py, src/cactus/setup/cactus_align.py
Tired of having to dig this out of the hal metadata.
=> Print cactus commit at top of log

build-tools/downloadPangenomeTools, src/cactus/refmap/cactus_graphmap_join.py
This fixes a crash on weird hairpin motif that seems to come up (on poorer assemblies?!)
=> Update to latest gfaffix

src/cactus/cactus_progressive_config.xml
Now properly turning off minimumBlockDegreeToCheckSupport check
=> Turning off the minimumBlockDegreeToCheckSupport flag.

README.md, ReleaseNotes.md, setup.py, src/cactus/cactus_progressive_config.xml, src/cactus/shared/common.py
I think the `minimumBlockDegreeSupport` fix may be worth making a patch release for.
=> prep release

doc/progressive.md
fixed incorrect relative links to markdown pages
=> fixed incorrect relative links to markdown pages

src/cactus/progressive/cactus_progressive.py, src/cactus/progressive/progressive_decomposition.py
Need this to better debug things like #819
=> output tree at beginning of cactus log

src/cactus/shared/common.py
=> Accept `ENOTEMPTY` in Singularity caching

README.md
See @thiagogenez 's PR here: https://github.com/ComparativeGenomicsToolkit/hal/pull/260
=> Update hal to include halAppendSubtree patch

build-tools/makeBinRelease, setup/impl/setup.c
todo: should probably just remove that whole check entirely...
=> Silience annoying (and misleading) log msg

.gitlab-ci.yml, .gitmodules, Dockerfile, Makefile, doc/progressive.md, src/cactus/maf/cactus_hal2maf.py
The interface (and even repo name) have completely changed:  Get cactus using the latest version.
=> Update to latest taffy

build-tools/downloadPangenomeTools, paf/tests/paf_align_test.txt, paf/tests/paf_chimp_align_test.txt
Also: fix up paf tests to pull data from gitlub rather than personal bucket.
=> Update to latest vg release

src/cactus/paf/local_alignment.py, src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py, src/cactus/shared/common.py
=> Toggle gpu on for containers

build-tools/makeBinRelease, doc/progressive.md, src/cactus/maf/cactus_hal2maf.py
as it is required for `cactus-hal2maf`
Also add a few gpu notes to the faq. 
Resolves #898
=> Add parallel to bin release

src/cactus/shared/common.py
@adamnovak ran into this crash when trying to make a pangenome on kubernetes with singularity binaries
```
File "/usr/local/lib/python3.10/dist-packages/toil/job.py", line 2875, in run
rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
File "/tmp/tmpy5phff2v/ef934d02fa4dcdfa6238e6d2cde1aeee/cactus/preprocessor/checkUniqueHeaders.py", line 61, in sanitize_fasta_header
cactus_call(parameters=cmd, outfile=out_fa_path)
File "/tmp/tmpy5phff2v/ef934d02fa4dcdfa6238e6d2cde1aeee/cactus/shared/common.py", line 824, in cactus_call
raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
RuntimeError: Command /usr/bin/time -v singularity -q exec -u -B /var/lib/toil/6f6487880fb85767bf766bb8fd6d51ba/bb2b/9f52:/mnt --pwd /mnt …
```
=> Try to harden singularity binaries mode

build-tools/downloadPangenomeTools
This properly fixes #971.  Thanks @danydoerr !!!
=> Update to GFAffix 0.1.4b

src/cactus/refmap/cactus_pangenome.py
By not outputting the paf file, it was impossible to manually resume a workflow at the `cactus-graphmap-split` phase.  This PR fixes that.
=> Add forgotten paf export to cactus-pangenome

src/cactus/refmap/cactus_minigraph.py
This saves a bit of time when doing the all-to-reference distance check to determine alignment order.
=> pre-sketch reference to speed up mash step

README.md, doc/pangenome.md
replaces the biorxiv link with the published version.
=> update pangenome paper citation

src/cactus/refmap/cactus_minigraph.py
By default, the input genomes are added to minigraph construction in decreasing order of their mash distance to the reference.  This is using the assumption that it will lead to cleaner graphs, and was implemented when constructing inter-species pangenomes.  
The problem is that for phased assemblies, the sex chromosomes dominate the distance.  For diploid human, for example, the maternal assembly will always have a much smaller distance to grch38 than paternal by virtue of sharing chrX.
This PR changes the mash sorting to do the whole sample at once.  So all the genomes of a given sample are first catted together, then their distance computed to the reference.  Ties are broken with their inddividual distances. 
This still isn't perfect, in a mix of haploid and diploid samples, the …
=> Better minigraph ordering for phased genomes

src/cactus/refmap/cactus_pangenome.py
need a refactor to put these in one place
=> fix consmemory option in cactus-pangenome

doc/pangenome.md, doc/progressive.md, src/cactus/cactus_progressive_config.xml, src/cactus/pipeline/cactus_workflow.py, src/cactus/progressive/cactus_progressive.py, src/cactus/refmap/cactus_graphmap_join.py, src/cactus/refmap/cactus_graphmap_split.py, src/cactus/refmap/cactus_pangenome.py, src/cactus/setup/cactus_align.py, src/cactus/shared/common.py, src/cactus/shared/configWrapper.py
=> Another --consMemory fix

Dockerfile
=> add libatomic to docker runtime for odgi

ReleaseNotes.md, doc/progressive.md, setup.py, src/cactus/shared/common.py
Normally wouldn't make a release for something so minor (especially as this would be the 3rd in 3 days), but I want this patch in the new HPRC graphs, and I want the HPRC graphs to be made with a release....
=> prep release 2.6.3

doc/progressive.md, src/cactus/maf/cactus_hal2chains.py
=> fix hal2chains typos

BIN-INSTALL.md, ReleaseNotes.md, doc/progressive.md, setup.py, src/cactus/shared/common.py
Wasn't planning on making a release so soon, but the new vg compatibility issue is already causing [problems](https://github.com/vgteam/vg/issues/4043)
=> prep release v2.6.6

bar/tests/poaBarTest.c, caf/tests/filteringTest.c
@adamnovak noticed the CI logs are quite big.  Looking at them, there's a lot of nonsense.  This PR cleans up some of the worse offenders
=> quieter unit tests

src/cactus/refmap/cactus_graphmap.py
Caught this making slurm fail on 400-way human alignment.
=> boost filter_paf_deletions job reqs

src/cactus/refmap/cactus_graphmap_join.py
This is a hack that double checks the header of the merged GFA and makes sure that any sample passed in via `--reference` appears in it.  It fixes the case where samples get dropped due to not being present in the first merged chromosome.
Resolves #1172
=> make sure all references in final gfa header

BIN-INSTALL.md, README.md
=> add wheel to pip update, apparently helps for newer python

build-tools/downloadMafTools
See https://github.com/ComparativeGenomicsToolkit/taffy/pull/32
Resolves #1201
=> update taffy to fix norm -d bug

src/cactus/shared/common.py
You can't run `docker` or `singularity` from inside the Cactus container.  This PR adds a clearer error message if someone tries to do so.  
Resolves #1222
=> More informative error message for nested containerization.

doc/pangenome.md, src/cactus/refmap/cactus_pangenome.py, test/evolverTest.py
Makes it a little simpler to experiment with inter-chromosomal events (has not been well tested at scale).
=> add cactus-pangenome --noSplit option

doc/pangenome.md, doc/sa_refgraph_hackathon_2023.md
Adds a link to this material that shows an example on how to make a HPRC subset pangenome (4 samples) then use it for read mapping and genotyping.  It should work on a 32-core 256-gig system (over a span of a few days).  
This was lurking in a branch during the hackathon, but I think it could serve as a useful example for others so there's no reason not to make it available in the main documentation..
=> Publish SA Hackathon Tutorial

README.md
Mail list section was convert to Getting Help, and moved up in the README to make it more obvious.  It now suggested help requests go to Discussions and issues are created for bugs and feature requests.
=> Update README.md to point to Discussions

src/cactus/refmap/cactus_graphmap_join.py
As it stands `--indexMemory` can be used to set the Toil job memory for all whole-genome indexing jobs (join phase of `cactus-pangenome`).  
But as shown here: [#1254](https://github.com/orgs/ComparativeGenomicsToolkit/discussions/1254#discussioncomment-7994849), some chromosome-level jobs can ask for large amounts on giant inputs. 
This PR hacks things so that `--indexMemory` now sets an upper limit on these jobs.  So if `--indexMemory 300GB` is used, then no job in `cactus-graphmap-join` will ask for more than `300GB`.  This of course will not prevent the jobs from actually running out of memory, but it at least lets the user have the options of trying it. 
I think moving forward, all cactus job memory specifications should go through a single function that applies upper and lower …
=> --indexMemory now sets upper-limit of all chromosome jobs

build-tools/downloadPangenomeTools
Thanks @AndreaGuarracino for [making](https://github.com/ComparativeGenomicsToolkit/cactus/issues/1257#issuecomment-1878050214) the release!!!
=> update to latest odgi

Dockerfile
=> Fix Dockerfile to include phast binares

doc/progressive.md
MAF-export continues to be a bottleneck and source of confusion.  That said, it has been vastly improved over the past couple years.  This PR expands the `cactus-hal2maf` documentation and adds some more examples.
=> Expand MAF export documentation

src/cactus/preprocessor/redMasking.py
Even though it's recommended to RepeatMask Progressive Cactus input, that's still no excuse for crashing when the input is completely unmasked.  But that's what happens as of v.2.8.0.  This PR fixes it.
Resolves #1327 
See https://github.com/ComparativeGenomicsToolkit/cactus/issues/1327#issuecomment-2021443396 for workarounds.
=> Fix bug where RED prerpocessing crashes if input 100% unmasked

src/cactus/maf/cactus_hal2maf.py
I introduced a really bad MAF bug in this commit: https://github.com/ComparativeGenomicsToolkit/cactus/commit/8157fe75e1206ec6d3a1a0801948873180663b03
While updating to the latest `taffy`, I swapped in `taffy sort` for `mafRowOrderer`.  They're basically the same, but not *exactly* the same in every case.  What happened is that in some cases, `taffy sort` would flip the first row of the MAF to something else (presumably with a lexicographically smaller contig name).  This breaks any downstream analysis (bigmaf conversion, taffy index, etc) that wants MAFs sorted by reference genome in first row on the positive strand. When combined with `--dupeMode single` it's even worse, because the "true" reference line is completely lost.  
This bug affects Cactus v2.7.2 and v2.8.0. 
Anyway, this PR …
=> Revert back to mafRowOrderer from taffy sort

src/cactus/refmap/cactus_graphmap_join.py, test/evolverTest.py
=> Fix bug where odgi squeeze input paths incorrect with --binariesMode docker

src/cactus/refmap/cactus_graphmap.py
#1383 reports an instance of this job requesting 56G but using 85G.  This PR boosts the scaling factor accordingly.
=> boost memory for filter_paf_deletions

doc/pangenome.md, doc/progressive.md
* Bit more explanation on pangenome filenaming. 
* Revised section about running on Slurm, with an example for ucsc/prism cluster best practices.
=> Documentation updates

BIN-INSTALL.md, ReleaseNotes.md, doc/progressive.md, setup.py, src/cactus/shared/common.py
this is a simple patch release that updates `vcfbub` and not much else.
=> prep release 2.8.4

doc/pangenome.md
=> fix typo in pangenome doc

build-tools/downloadPangenomeTools, pipeline/cactus_consolidated.c, src/cactus/pipeline/cactus_workflow.py, src/cactus/progressive/cactus_progressive.py
Rationale same as #1438 : avoid command line size blowup in presence of large star trees.
=> Introduce seqfile technology to cactus_consolidated

build-tools/downloadPangenomeTools
Update to latest vg and hal2vg versions that incorporate fixes for faster clipping on graphs with high path depth, most important of which is the new handle graph api to batch destroy paths.
=> Faster clipping tools

src/cactus/refmap/cactus_minigraph.py
=> fix recent regression where --mgMemory option crashes pipeline

src/cactus/paf/local_alignment.py
Someone ran into a case where the `merge_alignments()` job was asking for 400Gb of disk, which was too much for their cluster. 
It looks like this job is using a rough estimate of `size(chained(alignments)) ~= 5*(size(alignments))` which seems like it could be conservative, so this PR changes `merge_alignments` to exactly compute its own disk requirement, like some other jobs already do.
=> use exact disk estaimte for merge_alignments job

src/cactus/paf/local_alignment.py
This is pretty much the same patch as from #1497 (for the same reason) except for another job.
=> tighten disk usage estimate for tile_alignments

src/cactus/refmap/cactus_graphmap_join.py
See https://github.com/ComparativeGenomicsToolkit/hal/pull/313
=> update to hal that should work with new hdf5

build-tools/downloadPangenomeTools, src/cactus/refmap/cactus_graphmap_join.py
Will re-upgrade once https://github.com/marschall-lab/GFAffix/issues/16 is resolved.
=> Roll back to gfaffix v0.1.5b

BIN-INSTALL.md
=> remove --realTimeLogging option from example

src/cactus/refmap/cactus_pangenome.py
Oops, I merged #1599 too quickly: it only works with `cactus-minigraph` and not `cactus-pangenome`.  This PR fixes it.
=> make sure sequences read in seqfile order in cactus-pangenome

BIN-INSTALL.md, README.md, setup.py
=> Ratchet minimum Python up to 3.9 in light of Toil 8 requirement

doc/progressive.md, toil-requirement.txt
This version of Toil has a patch that makes slurm partitions specifiable on the command line.  Thanks @adamnovak !!
=> update to toil 8.1.0b1

build-tools/downloadPangenomeTools, src/cactus/refmap/cactus_graphmap_join.py
Letting a few more tests go through before merging, but this version's looking really good so far.
=> Update to gfaffix 0.2.1

src/cactus/refmap/cactus_graphmap_join.py
This reverts commit 057788350e4651fb470907bd7b24d4941a29c143.
=> Revert "sort --vg input by name for join"

src/cactus/refmap/cactus_minigraph.py
=> fix cactus-minigraph --restart bug

README.md, build-tools/downloadMafTools, doc/progressive.md, include.mk, pipeline/Makefile, test/evolverTest.py
This contains a bunch of mostly minor fixes to get Cactus building on MacOS.  I also added a section to the README about setting up dependencies on Mac.  
Starting  on a new Mac Mini, these steps were sufficient to build Cactus and successfully run `make evoler_test_local`.
=> Fix/update Mac build support

doc/progressive.md, src/cactus/shared/configWrapper.py
=> cap fastga cores to 8

src/cactus/paf/local_alignment.py
They lead to [crashes](https://github.com/thegenemyers/FASTGA/issues/18)
Todo: should we even be reconstructing these?
=> dont send all-n contigs to FastGA
