src/cactus/progressive/cactus_progressive.py

By default, singularity keeps the images (or at least the layers) under `~/.singularity`. On our cluster, the home directory is quota-ed and the Systems team recommends setting the environment variable `SINGULARITY_CACHEDIR`. When it is set, singularity will store the layers *and* images there, but cactus expects the image to be built and stored in `<jobStorePath>` (by changing the current  working directory). Because of that, cactus fails:
```
$ echo $SINGULARITY_CACHEDIR
/nfs/production/panda/ensembl/compara/muffato/singularity
$ cd /hps/nobackup/production/ensembl/muffato/sing/
$ cactus --binariesMode singularity job_store examples/evolverMammals.txt align2.hal
(...)
The workflow ID is: '729c211f-3d00-490a-aba7-6bf14063d76d'
(...)
Docker image path: …
```

When SINGULARITY_CACHEDIR is set, all images must be stored there

---

.travis.yml

Travis doesn't include the Docker username/password in PR builds
because they're "secret". This disables pushes on PR builds.

Testing a Travis PR build fix

---

src/cactus/progressive/cactus_progressive.py

The error message when docker or singularity isn't installed said to use `--binaryMode local` instead of `--binariesMode local`. `--binaryMode local` results in an unrecognized argument error.

fixed typo

---

src/cactus/progressive/cactus_progressive.py
src/cactus/shared/common.py

Added `--containerImage` option to specify a pre-built container image
instead of downloading a new one each time. Fixes issue #54.
Re-issue `singularity pull` command without the `--size` option if it
fails the first time since the `--size` option was removed in
singularity 3, but is required for version 2.3.
Clarify help text for the `--latest` option, it pulls new copy of the
latest image, but doesn't use a local copy as stated in the help.

Allow pre-built container, fix singularity 3 pull

---

.travis.yml
src/cactus/shared/common.py

`RoundedJob`'s super class got a new argument, `defer` in its `_runner()` method in the latest Toil (see discussion in https://github.com/DataBiosphere/toil/issues/2854).  We update it accordingly (and keep it optional to preserve backward compatibility)  
Should resolve #106

Update RoundedJob to work with latest Toil

---

src/cactus/pipeline/cactus_workflow.py
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/common.py

Port over the logic from [toil-vg](https://github.com/vgteam/toil-vg/blob/master/src/toil_vg/singularity.py) to explicitly download singularity images into a local sandbox.  This way they can be run from within docker appliances.    There is a performance concern here, as the images need to be regenerated every time they are run.  
When using a local file store, the old singularity logic of downloading an image once is preserved.  The new logic should only kick in on remote stores, that would have triggered an error with the old code.  
Kubernetes support is currently reliant on using a special toil branch:
```
pip install git+https://github.com/databiosphere/toil.git@72750c175eb84fde0e6d3302283f032edc39038b#egg=toil[all]
TOIL_AWS_SECRET_NAME=shared-s3-credentials …
```

Enable singularity with remote job stores in order to run on kubernetes batch system

---

README.md

Documentation (for cactus and toil both) should probably clearly mention that (at least for Slurm) the workDir directory needs to be a *shared* location -- not merely exist on login/compute nodes.  Currently, workDir defaults to the system's temp directory which will likely exist on each individual machine, but its files will be externally inaccessible.
Note the solution to this issue appears to be the user setting ~/tmp <-- https://github.com/DataBiosphere/toil/issues/2756

added crucial Slurm info for running on clusters

---

README.md

#152 rightfully points out that cloning the `sonLib` submodule is now required for `pip install`ing cactus.  But there's no mention of this in the installation instructions in the README, which has lead to some confusion.  This PR just adds a note about downloading submodules in the README.

Mention submodules in README installation instructions

---

.gitmodules
.travis.yml
Dockerfile
Makefile
README.md
include.mk
src/cactus/shared/common.py
test/evolverTest.py

`ktserver` and the `cactus` command line and `hal` output aren't covered by the current unit tests.  So relying on `make test`, as is implemented in Travis, can miss fairly major regressions.  
To get around this, I've been running the evolver example by hand and awful lot.  This script makes that slightly less annoying by having
```
make evolver_test
```
run the whole pipeline on the whole evolver tree twice: once on local binaries, and once with on (a locally built) docker image. 
If everything runs through, the test will pass if the output of halStats looks something like (<25% different) the output of the current version.  This ought to catch stuff like empty or corrupt hal files or missing genomes.  There are probably some easy improvements (coverage? exact sequence length / fasta …

Evolver test script

---

src/cactus/shared/common.py

The act of queuing up lots of child jobs in Toil can be slow.  Cactus used `ChildTreeJob` to spawn blast child jobs in a tree, limiting the number of children in each job.  But it passed queued jobs to the child jobs as arguments, and this caused pickling errors in recent version of Toil (#100).  
This PR is a quick re-write of `ChildTreeJob` to make the child tree without pickling any jobs.  To test it, I cranked down the maxChildJobs and blast chunk size, and ran evolver and the output looks correct.  It is difficult to assess the speed difference, though.  But if limiting the number of child jobs is all there is to it, it should work.  @joelarmstrong does this look reasonable, or am I missing the point?  
Should resolve #100

Don't pickle Jobs in ChildTreeJob wrapper

---

Makefile
src/cactus/cactus_config.xml
test/evolverTest.py

This is a quick patch to get master branch working until #151 is more properly resolved.  It simply overwrites `cactus_config.xml` with the settings in `cactus_progressive_config.xml` in order to make sure some of the old settings in the former (such as enabling normalization) don't get activated.

Harmonize cactus_config.xml and cactus_progressive_config.xml

---

src/cactus/blast/mappingQualityRescoringAndFiltering.py

This step was failing for me due to /tmp filling up. Setting a different TMPDIR in toil's environment wasn't working due to singularity issues, so I added a flag to the sort command so that toil makes a local temporary directory just for it. This seemed like a more robust solution.

Give 'sort' a temporary directory in mappingQualityRescoring

---

Makefile
README.md

Disable building static libraries and force no lua in Kyoto.
This needs to be merged after the  submodule Kyoto build and https://github.com/ComparativeGenomicsToolkit/kyoto/pull/3

Static only build of Kyoto

---

setup/cactus_setup.c

correctly check for cactus_setup required "options"

---

src/cactus/shared/common.py

redirect docker stdin to /dev/null if it is not supplied to allow running in the background
fixes #137

allow running cactus in background without blocking

---

src/cactus/blast/blast.py

doing 50 at a time may have been a bit extreme.  it led to over 1000 deletion jobs, without much apparent benefit in wall time.

Reduce number of DelteFileIDs jobs

---

Dockerfile
README.md
runtime/wrapper.sh
src/cactus/shared/common.py

The Cactus Docker images contain only the required binaries, but not the actual Cactus python package, which mean they can't be actually used to run Cactus.  This PR tacks on a pip install of cactus to the current Dockerfile.  Should resolve #113.

Make docker images runnable

---

.gitlab-ci.yml
Dockerfile

Clean up a few things
* don't `make clean` anymore in cactus.  This saves a compilation during the gitlab tests
* trim out unused apt packages
* more effort in multistage build to not include dev stuff in final image

Clean up dockerfile

---

.gitlab-ci.yml
Makefile
README.md
blast/cactus_coverage.c
setup.py
src/cactus/blast/blast.py
src/cactus/blast/cactus_blast.py
src/cactus/pipeline/cactus_workflow.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/projectWrapper.py
src/cactus/progressive/schedule.py
src/cactus/progressive/seqFile.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py
test/evolverTest.py

In order to more easily be able to hook in alternatives to the current lastz stage, as well as to make running big jobs easier, I'm trying to modularize the CLI a bit (without really touching the current interface).  Am working on 4 tools:
* `cactus-prepare` Take in a Seq file along with some job size and output location information, and spit out a modified Seq file, and list of `cactus` commands to run it incrementally
* `cactus-preprocess` Preprocessor only.  Changing existing tool to work more closely with seq file output by `cactus-prepare`
* `cactus-blast` Do the blast phase only.  This is the part that can be replaced with the alternatives in development
* `cactus` Option (or new command) to take input of `cactus-blast` on command line instead of starting input sequences

Begin modular CLI

---

.travis.yml
Dockerfile
README.md
requirements.txt
setup.py

* Change `Dockerfile` to install `toil[all]` instead of barebones version.  This lets, for example, it be used to read s3 job stores.
* Remove toil as a requirement in setup.py.  Having it as a requirement simplifies a single machine install, but will cause problems when using toil appliances
* Try to make docker image smaller by stripping debug symbols out of binaries
* Get rid of duplicate specification of python requirements (just keep version in setup.py)

Docker and install fixes

---

Makefile
test/evolverTest.py

`halStats --coverage` is more stable than `halCoverage` because it doesn't do any random sampling.  So use it in the gitlab tests instead to reduce variability in the output.  
Also: stop capturing pytest output and just let it print to screen.

Switch coverage test to use halStats

---

README.md
src/cactus/progressive/cactus_prepare.py

Get `cactus-prepare`, `cactus-blast`, `cactus-align` pipeline running on some non-trivial examples.  Using data from #181 as test case.

Continue work on modular interface

---

Dockerfile

it makes installation much easier
this came in as part of using standard make variables and getting the default configure behavior.
fixes #203

revert to always generating static libraries for kyoto

---

README.md
src/cactus/progressive/cactus_prepare.py
src/cactus/shared/configWrapper.py

When running cactus more than once on the same inputs, which happens frequently for numerous reasons, it helps a lot to not redo the preprocessing.  `cactus-prepare` is modified here to simplify this.
For example
```
cactus-prepare examples/evolverMammals.txt steps-output steps-output/evovlerMammals.txt steps-output/evolverMammals.hal --jobStore jobstore --preprocessOnly --preprocessBatchSize 10
```
gives this output.  The first command can be run once to preprocess the sequences and put their outputs into the output directory.  The second command will run `cactus` on this input without re-preprocessing
```
cactus-preprocess jobstore examples/evolverMammals.txt steps-output/evovlerMammals.txt --inputNames simHuman_chr6 simCow_chr6 simDog_chr6 simMouse_chr6 simRat_chr6 --realTimeLogging …
```

Option to only decompose preprocessing in cactus-prepare

---

src/cactus/shared/common.py

real commit is 56bc5d7 distinguish between signals and exit non-zero when reporting cactus
program failures
however, due to accidentally being pushed to master and then reverted, it doesn't show up in the pull request diff.

have cactus_call report if subprocess signaled or exited

---

src/cactus/blast/cactus_blast.py
src/cactus/setup/cactus_align.py

`--nonBlastInput` added to `cactus-align` to tell it not to add `id=0|` prefixes to fasta sequence names in order to match with the cigar.  Previously, this was toggled automatically in a confusing way. 
There's still work to be done with regards to outgroup alignments coming from other pipelines, but will hash that out when we have an example.  
@Robin-Rounthwaite This seems to work on a trivial example:
seq.txt
```
(simMouse_chr6:0.084509,simRat_chr6:0.091589);
simMouse_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simMouse.chr6
simRat_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simRat.chr6
```
prepare
```
rm -rf js ; cactus-prepare seq.txt ./test ./test/seq.txt ./test/out.hal --jobStore js
cactus-preprocess js …
```

Fix cactus-blast/align interface to better accept non-cactus input

---

src/cactus/pipeline/cactus_workflow.py
src/cactus/setup/cactus_align.py
test/evolverTest.py

As pointed out by @Robin-Rounthwaite the small `cactus-align` example in #216 with no outgroups and `--nonBlastInput` didn't actually work.  With `--binariesMode local` (how I usually test), it runs through, but with `--binariesMode docker` is crashed with the error below.
I've patched the error here, but clearly need to shore up testing.
```
Running command catchsegv 'cactus_coverage' '/tmp/toil-9534dde4-4f97-4c5d-8f43-936a1e2edb32-e1427db94b60421098ed79e7d63f0687/tmpmasona5i/0fee1a4d-e13a-46ea-bee7-8072213a367e/tmpj5f7s6rf.tmp' '/tmp/toil-9534dde4-4f97-4c5d-8f43-936a1e2edb32-e1427db94b60421098ed79e7d63f0687/tmpmasona5i/0fee1a4d-e13a-46ea-bee7-8072213a367e/tmp49s20b15.tmp'
kind-run_ingroup_coverage/instancef4ybkmls    cactus_coverage(+0x9f7e)[0x55becd07ef7e] …
```

fix cactus-align bug where no-outgroup case crashed

---

.gitlab-ci.yml
src/cactus/blast/cactus_blast.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_prepare.py
src/cactus/setup/cactus_align.py
test/evolverTest.py

When the `--wdl` options is passed to `cactus-prepare`, it will print a [WDL](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) script instead of command lines.  This could then be used, for example, to run on [Cromwell](https://github.com/broadinstitute/cromwell)
The motivation is that Cactus spawns millions of Toil jobs.  And while Toil supports many different batch systems in theory, the fact that there are so many jobs makes it unfit for many computing environments (namely hpc-style setups).  With `cactus-prepare`, the cactus workflow is decomposed into a handful of tasks for each node in the guide tree.  So long as each of these tasks is run on a large node,  they can be run efficiently with Toil's `singleMachine` batch system.  WDL is one simple way to chain these …

WDL support via cactus-prepare

---

README.md
doc/running-in-aws.md

Now that we're making releases, emphasize using them in the README.  Also fix bug in installation instructions where `toil-requirements.txt` was used before it was cloned.  
Should resolve #227.

Reorganize Installation instructions in README

---

reference/impl/buildReference.c
setup/cactus_setup.c

`cactus_reference` was [dividing by 0](https://github.com/ComparativeGenomicsToolkit/cactus/issues/181#issuecomment-625489666) in the presence of 0-length branches, and the resulting `nan`s caused it to loop forever.  
This PR fixes that particular division and, just to be sure, changes `cactus_setup` to add a little epsilon to 0-length branches to make sure they never end up in the cactus disk. 
Should resolve #181

Patch 0-length branch problem in cactus_reference

---

include.mk

Cactus is full of asserts, but they are switched off by default.  This PR turns them on: 
* Mostly because I'm bitter about #181 taking so long to reproduce and fix (#234).  Having the asserts switched on would have produced a semi useful error log rather than running indefinitely. 
* There are a few new features in development, and I think having asserts on will be especially valuable as we integrate them
I ran a little benchmark on 3 250Mb insect genomes (plus another 3 outgroups) on a dedicated 64 core machine.
Without asserts
```
real    391m9.762s
user    12474m44.832s
sys     569m36.468s
```
With asserts
```
real    402m2.147s
user    12580m36.629s
sys     573m7.268s
```
A couple percent difference seems reasonable.  Can reevaluate if it seems to cause disproportionately more …

Turn on asserts in C code

---

src/cactus/shared/common.py

Without this, in Python 3 on Toil 4.1.0, trying to run on Kubernetes with Singularity tools and an AWS job store, I get:
```
=========>
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 4.1.0-5ad5e77d98e1456b4f70f5b00e688a43cdce2ebe.
INFO:cactus.shared.common:Work dirs: {'/var/lib/toil/node-b177fa50-1926-4fda-9b7a-da27c621b219-1b6fc4a70f8334d5f732a04b5eb3b9f0/tmpp8ei2qpl/74f32c82-213d-47db-be10-1dd8e1b8f046'}
INFO:cactus.shared.common:Docker work dir: /var/lib/toil/node-b177fa50-1926-4fda-9b7a-da27c621b219-1b6fc4a70f8334d5f732a04b5eb3b9f0/tmpp8ei2qpl/74f32c82-213d-47db-be10-1dd8e1b8f046
Traceback (most recent call last):
File "/root/venv/lib/python3.7/site-packages/toil/worker.py", line 366, in workerScript
job._runner(jobGraph=jobGraph, jobStore=jobStore, …
```

Encode Singularity tool names before hashing

---

src/cactus/shared/common.py

`HOME` is not always set when running under the Toil appliance. `pathlib` can ask the system more directly for your home instead of only checking the environment.
This should fix #246.

Use pathlib to find home directory

---

src/cactus/shared/common.py

Somehow we forgot to import errno to actually detect and resolve download collisions.

Import errno which Singularity code needs

---

src/cactus/progressive/cactus_progressive.py

This gets Toil-driven timestamps in the logging output.

Let Toil drive logging

---

caf/impl/filtering.c

This is a little hack to speed up `containsMoreThanOneEvent()` by caching its results inside  `stPinchBlock`s.  It resolves #272 where `cactus_caf` could take extremely long on some outputs.  
I have a test running to make sure it behaves exactly the same as the old logic on the data mentioned in that issue, and won't merge until that passes.

Faster CAF

---

.gitlab-ci.yml
Dockerfile
Dockerfile.ci-base
Makefile

This essentially moves the `apt` updates from the gitlab setup in `.gitlab-ci.yml` and into `Dockerfile.ci-base` which is used to create a base image for CI jobs.  
This will hopefully resolve #253, as it's been especially bad [lately](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/56072), and should be a better fix for #224.

Switch base docker image for gitlab CI to one with more pre-installed

---

Dockerfile
README.md
setup.py
test/evolverTest.py

https://github.com/ComparativeGenomicsToolkit/hal/issues/108#issuecomment-620814684 points out that hal python tools aren't runnable in the cactus docker image. 
This PR ought to fix that.  As discussed in #225, something similar needs to be done with the binary release package.  
Don't like that there are a few duplicated hal scripts in the image (in particular, those from cactus's binary directory), but can live with it for now.

Add hal python tools to cactus docker

---

src/cactus/shared/common.py

Changing from the custom toil function `mkdir_p()` to the equivalent built-in `os.makedirs(exist_ok=True)`.  The built-in was added in python3.2.  If python2.7 compatibility is still desired, I'll just move the function from toil here.
I attempted to refactor this on toil, but it seems cactus has a dependency on it, and @adamnovak 's cactus integration test caught it!  https://ucsc-ci.com/databiosphere/toil/-/jobs/56501
Also removed some unused imports.

Use built in instead of mkdir_p.

---

ReleaseNotes.md
src/cactus/progressive/cactus_prepare.py
src/cactus/shared/common.py

I'll update the wiki, but this will necessitate that `getDockerRelease()` in common.py gets updated just before each release.

Get cactus-prepare ready for gpu release

---

BIN-INSTALL.md
Dockerfile
README.md
ReleaseNotes.md
build-tools/makeBinRelease
src/cactus/shared/common.py

#291 pointed out that the Kent tools that were included in the release are, despite being billed as "standalone", not in fact statically built.  As a result just copying them into the docker image left them unusable.  
The remedy here is:
* installing the required shared libraries in the Docker image (following the suggestion in #291 -- thanks @nathanweeks !)
* removing the Kent binaries from the static binary release of Cactus.  They are replaced with a blurb in the install instructions guiding the user how to install them themselves.
This has been enough trouble that I think it's worth making an assembly hub via Docker within the CI tests.  Still no phylop hal support but baby steps...

v1.1.1 patch to fix how kent tools included in releases

---

blast/cactus_convertAlignmentsToInternalNames.c

And here's `cactus_convertAlignmentsToInternalNames` of all things about to bring down a big toil run due to running out of memory:
```
8621 root      20   0  229.0g 229.0g    428 R  99.3  95.4  55:50.01 cactus_convertAlignmentsToInternalNames tmpws3w08gd.tmp tmpxthgv3k_.tmp --cactusDisk <st_kv_database_conf type="kyoto_tycoon"> ...<kyoto_tycoon database_dir="fakepath" host="172.31.26.9+ 
```

Fix memory leak in cactus_convertAlignmentsToInternalNames

---

src/cactus/blast/cactus_blast.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_progressive.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

Got this when finishing bar on the 55-way minimap2 alignments
```
Deadlock encountered: The workflow is service deadlocked - all 1 running jobs have been the same active services for at least 60 seconds
``` 
This is because the hack to override deadlockWait that's in `cactus` somehow never made it to `cactus-align`.  This PR makes sure the same overrides (including setting the deadlockWait to 3600) that are in `cactus` are also in `cactus-blast`, `cactus-align`, etc.

Apply toil overrides consistently for all cactus-* scripts

---

caf/cactus_caf.c
src/cactus/setup/cactus_align.py
src/cactus/shared/configWrapper.py

Some filters in caf aren't playing nicely with star tree / pangenome inputs.   So far I've found
* The megablock filter (0.05% of all possible transitive support required for blocks >= 10) basically pulls apart nearly all the blocks when giving reference-based input via star tree, as n/n^2 quickly drops below 0.05 as the number of sequences increases.  Hopefully just toggling it off will help. 
* The "singleCopy" alignment filter doesn't keep duplications out of the graph as one might expect, because it doesn't get applied to secondary alignments.  Changing the filters that previously only ran on primary alignments to run on both primary and secondary alignments.  The default filter `filterSecondariesByMultipleSpecies` remains unchanged in that it only runs on secondaries.,

CAF tweaks

---

README.md
ReleaseNotes.md
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/shared/common.py

The segalign repeat masker was [fixed up to include cactus_covered_intervals](https://github.com/gsneha26/SegAlign/issues/42#issuecomment-701865527).  But whereas cactus ran it with `--origin=one`, it seems that segalign runs it with (effectively) `--origin=zero`.  This only became apparent on a large run when `cactus_fasta_softmask_intervals.py --origin=one` crashed out on an interval that began with 0.    
Anyway, this patch should hopefully sync the options up properly.

GPU Repeatmasking fix

---

bar/cactus_bar.c
bar/impl/endAligner.c
bar/impl/flowerAligner.c
bar/impl/poaAligner.c
bar/inc/endAligner.h
bar/inc/flowerAligner.h
bar/inc/poaAligner.h
bar/tests/runEndAlignment.c
src/cactus/cactus_progressive_config.xml
src/cactus/pipeline/cactus_workflow.py
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/common.py

(Stacks on #334)
abPOA requires memory [quadratic in sequence length](https://github.com/yangao07/abPOA/issues/14), so the current version only usable up to a few tens of kb.  
this PR splits the MSA problem into windows (default size =10kb) left-to-right on the input sequences, and runs abPOA on each window.  What it doesn't do (yet), is try to be clever about window boundaries.  
(the whole poa workflow remains experimental and undocumented pending further testing, but we hope it will help with human pangenome graphs where the usual progressive decomposition doesn't apply)

Windowed POA

---

.gitlab-ci.yml
.travis.yml
Dockerfile
Makefile
blast/Makefile
blastLib/Makefile
check/Makefile
include.mk
preprocessor/Makefile
preprocessor/lastzRepeatMasking/Makefile
reference/Makefile
setup/Makefile
src/cactus/blast/cactus_blast.py
src/cactus/pipeline/cactus_workflow.py
src/cactus/pipeline/dbServerCommon.py
src/cactus/pipeline/dbServerTest.py
src/cactus/pipeline/dbServerToil.py
src/cactus/pipeline/ktserverControl.py
src/cactus/pipeline/redisServerControl.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/projectWrapper.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py
src/cactus/shared/experimentWrapper.py
test/evolverTest.py

This PR contains the changes made to add Redis  as a database option to Cactus beside the currently used database, Kyoto Tycoon. The main changes are:
- Adding [Redis](https://github.com/redis/redis) and its C client library, [hiredis](https://github.com/redis/hiredis), as submodules to Cactus. I didn't use their Ubuntu packages since they are several versions behind the latest ones;
- redis: [4.0.9](https://packages.ubuntu.com/bionic/redis-server) (the latest is [6.0.8](https://github.com/redis/redis/tags))
- hiredis: [0.13](https://packages.ubuntu.com/bionic/libhiredis-dev) (the latest is [1.0.0](https://github.com/redis/hiredis/releases))
(Maybe we can change it to use the ubuntu packages if new submodules make it difficult for users to build cactus but in that case we may not be able …

Adding Redis as a database option to Cactus

---

include.mk

Regarding the issue mentioned here https://github.com/ComparativeGenomicsToolkit/cactus/commit/d3d6361914091a97a56946f56763ead42e84ff90#commitcomment-43877817 
When `hiredis` is not installed on a system we expect to compile cactus with no error. In that case cactus wouldn't support redis but it can be run using kyoto tycoon as before.

Enabling cactus to compile successfully even if hiredis is not installed

---

.gitlab-ci.yml
README.md
bar/cactus_bar.c
bar/impl/poaBarAligner.c
bar/inc/poaBarAligner.h
bar/tests/poaBarTest.c
build-tools/downloadMiniTools
preprocessor/Makefile
preprocessor/cactus_softmask2hardmask.c
preprocessor/lastzRepeatMasking/cactus_fasta_softmask_intervals.py
setup.py
src/cactus/cactus_progressive_config.xml
src/cactus/pipeline/cactus_workflow.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/dnabrnnMasking.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/shared/common.py
src/cactus/shared/configWrapper.py
test/evolverTest.py

* `--alphaMask` option added to `cactus-preprocess`
* `--ignoreSoftmasked` option added to `cactus-graphmap`
* `--maskFilter` option added to `cactus_bar` (set using `partialOrderAlignmentMaskFilter` in the config given to `cactus-align`)
Together, these give more fine-grained control for keeping certain subregions from ever being aligned (while preserving their sequence in the output)

Graphmap masking pipeline

---

.gitlab-ci.yml
Dockerfile
build-tools/downloadPangenomeTools
setup.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

This workflow is to speed up whole genome pangenome construction by doing each chromosome separately. The steps are:
* Preprocess the full genomes with `cactus-preprocess`
* Map the full genomes to the whole-genome mingraph GFA with `cactus-graphmap`
* Run new tool `cactus-graphmap-split` which uses the minigraph rGFA tags and PAF alignments to split the GFA, PAF, and input Fastas by chromosome
* Call `cactus-align` on each chromosome input set created above (with a new wrapper script)
I'm hoping this will do 90 genomes in < 24 hours wall-time on 20 32-core nodes.

[WIP] chromosome-by-chromosome cactus-graphmap workflow

---

src/cactus/blast/cactus_blast.py

There are no tests for the `--restart` logic, so these are always sneaking into master. Should resolve crash mentioned in #381

fix cactus-blast --restart bug

---

blast/cactus_convertAlignmentsToInternalNames.c
src/cactus/shared/common.py

This is an attempt to address the error from the log posted here: https://github.com/ComparativeGenomicsToolkit/cactus/issues/301#issuecomment-738192236 where a `--workDir` with lots of space was apparently given, but cactus ran out of space while running `sort` within `cactus_convertAlignmentsToInternalNames`.  
There's probably a more thorough review in order to make sure that `--workDir` overrides the TMPDIR environment variables under all circumstances.

Force cactus_convertAlignmentsToInternalNames to only write in filetsore while sorting

---

build-tools/downloadPangenomeTools
src/cactus/cactus_progressive_config.xml
src/cactus/pipeline/cactus_workflow.py
src/cactus/pipeline/cactus_workflowTest.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_refmap.py
src/cactus/setup/cactus_align.py

`cactus-graphmap-split` use the minigraph alignments to partition a set of input contigs into reference chromosomes.  I've been doing this by just picking the chromosome to which a given contig maps to the most.  But this seems to be break down for smaller chromosomes (notably chr21) as they sponge off all kinds of partially and/or ambiguously mapping contigs leading to big messy graphs.  This adds PR adds 2 filters to exclude contigs if
* they don't overlap the given reference by enough or
* they aren't unique enough (determined by comparing to second-best assignment). 
Contigs that fail these filters don't get assigned a chromosome.  They can be viewed in the fake `__AMBIGUOUS_SEQUENCES__` bin where they are saved.  The defaults for these filters only filter out a few (small) input …

Filter ambiguously mapped contigs when splitting into chromosomes

---

.gitlab-ci.yml

Our CI system now has a caching mirror for Docker Hub. This sets CI to use it, in case we actually pull any Docker containers.

Add support for Docker Hub mirror for CI

---

build-tools/downloadPangenomeTools

I hacked together a few tools while implementing the `cactus-graphmap` pipeline.  They ended up in these repos, and are necessary to run the pipeline:
https://github.com/glennhickey/paf2lastz
https://github.com/glennhickey/mzgaf2paf
This PR moves them to
https://github.com/ComparativeGenomicsToolkit/cactus-gfa-tools

Update repo for GFA tools

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap.py
src/cactus/shared/common.py

When `cactus-graphmap-split` assigns contigs to chromosomes, it uses alignment coverage from a PAF file.  There is a coverage filter (default=80%) that is applied to make sure only contigs that align well enough to a chromosome get assigned.  The PR fixes a bug in this filter where the query interval was used to compute coverage without taking into account softclips.  Now it's changed to use the mapped bases field which should be much more stringent. 
This PR also adds the `--refFromGFA` option to `cactus-graphmap` that will use the GFA to infer alignments of the reference sequence (instead of realigning with minigraph as done by default).  The idea is that this will give a more complete alignment (for chrY, for instance, less than half the reference sequence aligns to the minigraph). …

Fix graphmap-split filter

---

README.md
build-tools/downloadPangenomeTools
doc/pangenome.md
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/dnabrnnMasking.py

It looks like there are too many unaligned bubbles in the whole-genome graphs coming out of the pangenome pipeline.  Especially in chr8 and chr21.  In theory, we hope `dna-brnn` catchces all such regions so we can mask them out.  In practice, it doesn't model everything.  So this is a hack to explore being more aggressive with masking.  This will help make cleaner graphs, and isolate/quantify problems coming from caf/bar phases:
* `--maskPAF` option added to `cactus-preprocess`.  It takes an input PAF file, computes the gaps in coverage, and merges these intervals with those found with `dna-brnn`. 
I took 2 shortcuts to get this implemented quickly in order to test:
1. `--maskPAF` can only be applied in conjunction with `dna-brnn` (which is the main use case right now, but not that hard …

Preprocess option to mask PAF coverage gaps in addtion to dna-brnn regions

---

Dockerfile
bar/impl/poaBarAligner.c
build-tools/downloadPangenomeTools
src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/dnabrnnMasking.py
src/cactus/refmap/cactus_graphmap_split.py

I caught `cactus-bar` aligning together sofmasked sequences when they should have been ignored due to `--maskFilter`.  This PR attempts to fix this (one glaring bug found so far). 
It's crucial that this logic work if we're going to cut centromeres out post hoc in the hpp pipeline.

Fix bar mask filter bug

---

ReleaseNotes.md
src/cactus/progressive/cactus_prepare.py

`cactus-prepare` uses `bytes2human` and `human2bytes` while parsing disk and memory sizes.  But `bytes2human` sticks a space between the number and unit, meaning it can't be used as a single cli parameter.
Resolves #426

Make sure bytes2human values can be used on cli

---

build-tools/downloadPangenomeTools
build-tools/makeBinRelease
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_split.py

The pangenome pipeline currently uses `minigraph` to split the data into reference chromosomes.  This is for simplicity and consistency, as it's already being used to make the alignment anchors.  But it's been a struggle coming up with a coverage threshold that works for small contigs.   
This PR adds a second pass of contigs that can't be assigned using the existing minigraph logic.  They are remapped to the linear reference with minimap2, and then the same splitting logic is applied on these alignments.  In practice, the minimap2's base level alignments can dramatically increase the coverage of some small contigs, so they are "rescued" from the ambiguity pile by this procedure. 
This PR also relaxes the minigraph coverage computation to count gaps between minimizers (up to a given …

minimap2 fallback in graphmap-split

---

src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/checkUniqueHeaders.py
src/cactus/preprocessor/cutHeaders.py

Cactus makes some pretty heavy assumptions about fasta headers.  They are enforced by default via the `CheckUniqueHeaders` preprocessor.  In addition to most non-alphanumeric characters, common things like spaces are rejected (usually it's safe to ignore everything after the first space).  There are good historical reasons for all this. But it can be a bit onerous to have to manually rename 100's of gigs if fasta just to meet the naming conventions.  This is the position I'm in at the moment with a bunch of human genomes with headers that can look like:
```
>chr1
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
>HG02055#1#h1tg000001l
```
So I've added a `cutHeaders` preprocessor.  It cuts prefixes and suffixes that occur …

New preprocessor: CutHeaders

---

build-tools/downloadPangenomeTools
preprocessor/cactus_softmask2hardmask.c
setup.py
src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/dnabrnnMasking.py
src/cactus/preprocessor/fileMasking.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py

In the pangenome pipeline, I want to (at least for now) mask out centromeres using both dna-brnn, as well as gaps in the minigraph minimizers.  Unfortunately, the sequences softmasked by both approaches requires running the preprocessor (or mapping) twice.  This PR adds the `--maskFile` option that allows something like:
* preprocess with dna-brnn
* map with graphmap
* preprocess with paf from graphmap to add in gaps
The alternative is
* map with graphmap
* preprocess with dna-brnn and paf
* map with graphmap again (to make sure no dna-brnn'd regions in paf)
Both ways are ugly, but I like the first one a little more as it means less dna-brnning over repeated runs.  
I think bar can deal directly with minimizer gaps (as opposed to needing masked sequence) just be using the max-length …

Add preprocess interface to directly mask by input paf/bed file

---

src/cactus/refmap/cactus_graphmap_join.py

A few small fixes from having run it through a few times on full data sets. 
Note the vcf export relies on functionality not yet in a vg release, so it won't yet work in any Cactus Docker images or binary releases.

cactus-graphmap-join cleanup

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

This allows to produce a single, whole-genome HAL at the end of the pangenome pipeline by merging up the chromosomal HALs that it currently outputs.

HAL merging option in cactus-graphmap-join

---

bar/impl/bar.c

Reading the maximum sequence length for bar (from "bandingLimit", as was previously done) as opposed to hardcoding fixes the `make evolver_test_poa_local` gitlab test.

Read max size from config

---

examples/evolverMammals.txt
test/evolverTest.py

The s3 bucket they were in is gone, so use github instead. Thanks to @DailyDreaming for the heads up.

Fix links to evolver mammals

---

bar/impl/poaBarAligner.c

abPOA 1.2.0 [can align longer sequences via minimizer-based seeding](https://github.com/yangao07/abPOA/issues/14#issuecomment-841636128).  This is very interesting for Cactus which presently relies on some repurporsed stitching code for >10kb alignments that is a suspected sources of misalignments in some complex regions.  
In Cactus, this logic is controlled by `partialOrderAlignmentWindow`, so increasing it should be a good test of what this improves.  
Speaking of the config, now is also probably a good time to add all the abPOA parameters for scoring and seeding so they can overridden if desired.

Update to abpoa 1.2.0

---

bar/impl/bar.c
bar/impl/poaBarAligner.c
src/cactus/cactus_progressive_config.xml
src/cactus/setup/cactus_align.py

abpoa anchoring crashes on the full pangenome, even when using the same stitching/window size logic as before in bar.  This PR disables it by default in the config.

Disable abpoa anchoring (and sync with master)

---

Dockerfile

Inspired by https://github.com/vgteam/vg/pull/3300
This is to try to fix Travis errors [like](https://travis-ci.org/github/ComparativeGenomicsToolkit/cactus/jobs/772393350)
```
Step 17/32 : FROM ubuntu:bionic-20200112
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Makefile:216: recipe for target 'docker' failed
make: *** [docker] Error 1
The command "if [[ "$CACTUS_BINARIES_MODE" == "docker" ]]; then
if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
make push
else
make docker
fi
fi
" failed and exited with 2 during .
```

Switch from docker hub to google for ubuntu base image

---

Dockerfile
bar/impl/poaBarAligner.c
build-tools/makeBinRelease
src/cactus/cactus_progressive_config.xml
test/evolverMammals-default.comp.xml
test/evolverTest.py

* remove old match/mismatch flags -- they're superseded by matrix
* fix the evolver mammals test baseline to be based on pecan / lastz, and crank up the threshold to 0.0375
* bump `-march` from `nehalem` to `haswell`.  this fixes an obscure abPOA segfault deep in the 90-way pangenome.

abpoa updates

---

src/cactus/cactus_progressive_config.xml
src/cactus/setup/cactus_align.py

With seeding enabled, abpoa uses minimizers to find anchors to speed up alignment.  This works well in practice and comes at a very minimal cost in accuracy, so it's probably best on by default.  
I'm leaving it off in `--pangenome` mode for now, though, where runtime is less of an issue.

enable poa seeding by default (except in pangenome mode)

---

src/cactus/progressive/cactus_progressive.py
src/cactus/setup/cactus_align.py

New option `--consCores` required for non-single-machine batch systems.  But check to enforce this had typo when comparing against old toil naming

Fix typo in singleMachine name check

---

src/cactus/shared/common.py

Right now stderr from `cactus_consolidated` gets printed to the log right after it runs.  This PR changes the behaviour to, when `--realTimeLogging` is used, log it while it is running.  
So in the not-so-hypothetical case where a job is taking forever on Terra, and the only information accessible is stderr, at least we'll be able to check how far it's gotten.

Log cactus_consolidated stderr messages in real time

---

src/cactus/cactus_progressive_config.xml

Some CAF paramters were [recently changed](https://github.com/ComparativeGenomicsToolkit/cactus/commit/3acf03c4ced50145963bbb12fad77fbf02246f71) in order to be able to toggle off realign by default.  
It seemed to work well enough, but one of these changes (going from `trim="0 0"` to `trim="3"`) mysteriously increases CAF running time from 7 hours to 57 hours on a mouse/rat + outrgoup alignment.  The running time hit comes from giant blocks of only mouse inside `containsMoreThanOneEvent()` when filtering secondary alignments.  Is this a coincidence? a bug?  I don't know, but it's very reproducible.  
So here I'm making the minimal change that keeps our (overtrained on) evolver test passing while setting trim back to 0.

Rejig CAF parameters

---

README.md
ReleaseNotes.md
build-tools/downloadPangenomeTools
build-tools/makeBinRelease
include.mk
src/cactus/cactus_progressive_config.xml
src/cactus/progressive/cactus_progressive.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

I'd [changed the trimming parameters](https://github.com/ComparativeGenomicsToolkit/cactus/commit/79763f2b8b246d3188e98281ac0182b8817a5580) right before making release 2.0.0 as it worked okay on small tests and fixed a case where mouse/rat was getting bogged down in a trivial CAF filter. 
But, the new parameters crashed out while building pangenome chr4, so I'm reverting back to the previous defaults.  These are more tested, but have the known issue of being slow in some cases (for unknown reasons) while filtering secondary alignments.  
The fact that the program is so sensitive to these parameters in terms of both crashes and running time is definitely cause for concern and needs to be looked into asap.

Revert last-minute caf parameter tweaks

---

build-tools/downloadPangenomeTools
build-tools/makeBinRelease
include.mk

libxml2 threw a bit of a wrench in the static binaries building procedure, which was already tricky due to hdf5.  This PR scripts out all the hacking I needed to do, so hopefully it will be much easier going forward. 
@diekhans you were talking about doing this in Docker at some point.  In theory (I haven't tested, of course) now it should be trivially doable in any Ubuntu 18-based image (such as Cactus) by running [the apt install command from the Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/c489c085ada05763905f789933cb3d81debe866f/Dockerfile#L4) followed by `make binRelease`

More self-contained static builder script

---

bar/impl/poaBarAligner.c

I've run into 2 cases where abpoa segfaults within `abpoa_free()` and I can't figure out why:
* pangenome chr16 when enabling contig splictting via miniamp2 anchors
* pangenome chr4 when using blocktrim 8
In both cases, address sanitizer and valgrind don't find anything except the line that crashes where uninitialized memory is freed.  It turns out that @ekg has been grappling with a similar issue in PGGB.  The mysterious thing is that neither he nor I can reproduce it with the `abpoa` command line, which makes it impossible for Yan to debug. 
Erik thinks it may be due to the number of sequences (> 1024) which I think may be consistent with what I've seen (it certainly doesn't seem related to sequence length).  
Anyway, here I'm hacking in an option for Cactus to, instead of calling the …

Add abpoa debug stuff

---

ReleaseNotes.md
src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/cutHeaders.py
src/cactus/refmap/cactus_graphmap_split.py

So now something like
```
<preprocessor memory="littleMemory" preprocessJob="cutHeaders" cutBefore="#" cutBeforeOcc="2" cutAfter="#" active="1"/>
```
can be used to transform `>HG01109#2#JAHEOZ010000001.1#MT` into `>JAHEOZ010000001.1`
(the old logic with just cutBefore="#" would have given `>MT`)

Hack in option to fine-tune fasta header cutting

---

bar/impl/poaBarAligner.c
bar/inc/poaBarAligner.h
bar/tests/poaBarTest.c

Quick fix to use the bar reconciliation process when any of the unaligned sequences is longer than the maximum threshold.

Fixing bar reconcilliation

---

src/cactus/refmap/cactus_graphmap_join.py

The pangenome graphs coming out of cactus have lots of small gaps.  In this msa these show up like
```
AA-A
A-AA
```
In the graph, they are bubbles that contain redundant traversals (often just a single-base node that is duplicated).  Some large-scale versions of this are inherited from underalignments out of minigraph.  But many of the small ones seem due to cactus's stitching aka reconciling code in bar.  
[GFAffix](https://github.com/danydoerr/GFAffix/) is a cool new tool that can quantify and correct such cases.  As far as I know, its algorithm is effectively similar to `vg mod --normalize`.  Since vg's already in the pipeline, I'm adding an option to use it for normalizing.  I've had trouble with it in the past, but I'm hoping it was due to underlying libbdsg bugs that have since …

Add optional normalization to graphmap-join

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

Temporarily use patched vg binary until next release.  
This allows the pangenome pipeline to run on genbank names that contain dots.  The older vg cuts everything after the dot leading to name conflicts

Use patched vg

---

Dockerfile

Make sure same base images used for both build stages.
This reverts some hacks to speed up docker builds on gitlab (using base with some preinstalled packages) and not crash on travis (use google mirror).  Something similar can be applied down the road (ideally, using the comparative genomics quay and more consistent images)

Harmonize base images

---

Dockerfile
bar/Makefile
build-tools/makeBinRelease
pipeline/Makefile

By default, abpoa will compile its simd code with `-march=native`.  This leads to non-portable binaries and is inappropriate for the binary and docker releases.  
I'd gotten around this by taking a page out of vg's playbook and using `-march=nehalem` everywhere ,abpoa included.  But now I'm running into obscure segfaults in the abpoa simd code that only happen with the releases.  
So out of desperation, I'm trying to simplify things a bit by:
* never using `-march` (I think by default it should make something very portable for x86 64)
* using variables abpoa expects in order to build it with `-msse41`
* not modifying abpoa in anyway (keeping local fork identical to upstream).  this means reverting little makefile hacks I'd used previously, as well as changes to make it compile without …

Revert abpoa tweaks and stop using -march

---

Dockerfile
build-tools/makeBinRelease

This seems to resolve a segfault that's come up in the pangenomes. 
It's a bit of a shame to bump up the minimum requirements for cactus releases like this given the current build works on almost all cases, but better to have something stable.  Hopefully the underlying issue gets fixed in abpoa and we can go back to sse4.1

Use avx2 instead of sse4.1 when building abpoa

---

README.md
build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

[GFAffix](https://github.com/marschall-lab/GFAffix) is a tool that merges away redundant graph nodes, much in the same way as `vg mod -U`.  This PR adds it as a postprocessing option in `cactus-graphmap-join`.  It'll let us run tests to see if using it instead of mod  helps in practice

Add GFAffix option to smooth out pangenome graphs

---

ReleaseNotes.md
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/shared/common.py

This fixes up some issues with normalization, especially with gfaffix.  It's now run properly, and done *after* clipping.  This change and a couple others are pulled over from #544, which, I think, I have to give up on.

Fix pangenome normalization bugs

---

ReleaseNotes.md
build-tools/downloadPangenomeTools
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/dnabrnnMasking.py
src/cactus/preprocessor/fileMasking.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/paf_to_lastz.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

(Includes #551)
The pangenome pipeline doesn't work great yet on centromeres, so it's best to mask them out in the preprocessor.  Way back at the beginning, I was clipping them out entirely, and putting the fasta pieces through cactus.  But then I switched to softmasking them, and having Cactus ignore them (`--maskFilter option in `cactus-graphmap` and `cactus-graphmap-split`, then `--barMaskFilter` option in `cactus-align`). They could be removed later with `cactus-graphmap-join --clipLength`
The advantages: original sequences are preserved, intact, in the HAL
The disadvantages: It's a hassle to pass through the masking information at every step.  Especially in BAR, where I wonder if masked sequences at the edges of recoverable chains aren't leading to underalignment. 
So I'm going to …

Dust off preprocessor contig-clipping

---

build-tools/downloadPangenomeTools
src/cactus/refmap/paf_to_lastz.py
src/cactus/setup/cactus_align.py

Sending the minigraph nodes into Cactus as contigs can cause problems (#544).  Using stable coordinates from minigraph to get around this was [even worse](https://github.com/ComparativeGenomicsToolkit/cactus/pull/544#issuecomment-885155823).  
This PR works directly on the PAF input given to `cactus-align`, where all target sequences get replaced with query sequences that map to them.  In doing so, it avoids introducing conflicts from the graph annotation, all event name hassles, as well as changes to `cactus-graphmap-split` which, being upstream, can keep making use of minigraph node ids.  
On chr20 for the 90-way pangenome, the conversion takes `3min` and `800M` RAM.  The output PAF is `1.1G` vs `179M` for the input, so I think this should scale up to chr1 (and probably some low-hanging …

drop minigraph event when reading paf in cactus-align

---

src/cactus/refmap/cactus_graphmap_join.py

`cactus-graphmap-join` can now make the giraffe-specific indexes while it's working on the deconstructed VCF.  Toggle on with `--giraffe`. 
Also, the VCF is no longer produced by default and will only happen now with `--vcf`

Option to make giraffe indexes

---

build-tools/downloadPangenomeTools
preprocessor/cactus_softmask2hardmask.c
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/setup/cactus_align.py

* tune chromosome splitting parameters for the umpteenth time.  now geared towards sequences that have been clipped (rather than masked) in the prprocessor
* the recently added stable coordinate conversion / minigraph event dropping logic made optional (via config) and deactivated by default.   it seems to hurt more than it helps, especially for vcf comparison metrics.  
* small patches to graphmap-join

Pangenome updates

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

HPRC graphs look best when clipping out centromeres before running cactus.  This lead to hal files with a bunch of fasta fragments with `_sub_X_Y` suffixes.  These get removed when writing GFA W lines downstream, but remain in the HAL.  They are especially annoying in the GRCh38 contigs in the CHM13-based graph.  
Anyway, this PR adds an option to take the centromeres out of the original fasta files and paste them back into the HAL.

Option to add clipped centromeres back to HAL

---

.gitlab-ci.yml

pip seems to be [taking forever](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/94559) to install Toil in our CI, since the kubernetes reboot.  Looking very quickly [here](https://stackoverflow.com/questions/65122957/resolving-new-pip-backtracking-runtime-issue) it seems it may be related to a regression in a newer version of pip?
This PR tries to patch this by adding `--use-deprecated=legacy-resolver` to pip install commands in CI.

Try to speed up ci by using pips depreacted resolver

---

Dockerfile

Quick fix that (along with fixing up the quay variables in gitlab) should get CI running again. 
I think @adamnovak has a better fix that gets the registry cache going again https://github.com/vgteam/vg/pull/3476 that we probably want to pull in soon.

Use quay.io instead of dockerhub for ubuntu base image

---

README.md
src/cactus/refmap/cactus_graphmap_join.py

The use case is CHM13-based graphs.  By default, the xg's come out with just CHM13 paths, with everything else in the GBWT.  But to run `vg surject` and now `vg call` with a GRCh38-based reference, we need to add back GRCh38 to the xg.  I've been doing this by hand which is error-prone.  This PR automates the process...

Script in option to add back references to xg

---

build-tools/downloadPangenomeTools
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap.py

minigraph can produce split mappings that induce huge deletions in the graph.  This doesn't happen often, but I don't seem to be able to reliably prevent it using the existing block filters.  
This PR adds an optional pass right after the creating of the paf mapping from the assembly to minigraph:  it looks at consecutive query intervals, computes roughly where their corresponding target intervals fall on the nearest reference path (in the mingraph), and if the result is a novel deletion above a certain threshold, the paf is filtered.  The filtering just removes the side of the deletion with the fewest aligned blocks (process is repeated until nothing removed on one iteration).
Testing this finds a bunch of such mappings involving chr1 telomeres (which caused a big bubble in the first …

Add deletion filter option to cactus-graphmap

---

pipeline/impl/convertAlignmentCoordinates.c

A fasta header that's just an id prefix with nothing after, ex
```
>id=chimp|
ACACACAC
```
leads to a really cryptic error in `halAppendCactusSubtree` (#582).
This is a case that arises from an error that I don't think we want to handle.  This PR adds a check at the beginning of `cactus_consolidated` to fail with a message if it's encountered.
@benedictpaten I'm PRing this against your branch instead of master to avoid a merge conflict down the road, as the function in question is modified in your branch.

Abort with error if stripping unique id leaves empty header

---

Makefile
bar/inc/poaBarAligner.h
include.mk

@benedictpaten This may help you build?
suggest a trying a fresh clone of the branch before merging.  Make sure submodules up to date, and `arm` is defined before building
```
git submodule update --init --recursive
make clean
arm=1 make
```
This builds on clang/graviton.  But I get weird Python locale errors when trying to run tests on that machine, but these are completely unlreated to abpoa compilation so you may have more luck.  
It also seems to cause runtime errors on x86 (which definitely *are* related to abpoa compilation).  I'll look into these, but in the meantime the gitlab tests won't work...

Hack in ARM support

---

Makefile
bar/impl/poaBarAligner.c

looks like `abpoa` recently turned seeding off by default (good idea).  this fixes the debug option in cactus to use the new options when running from the command line.

Fix command line abpoa runner to use latest cli interface

---

setup.py

Resolves #626.  Thanks @EricDeveaud for the suggestion.

Use "sys.executable -m pip" instead of "pip" in setup.py

---

src/cactus/progressive/cactus_prepare.py
test/evolverTest.py

This fixes a longstanding annoyance with WDL workflows.  Previously, a task was called to stitch the intermediate results of each subjob into the final hal, and these tasks were called in series.  This requires tons of overhead for not that much compute.  
This PR batches this up (`--halAppendBatchSize` default=12) so that several alignments can be stitched in each task. 
It also uses a canonical ordering so that multiple runs on the same input will always produce WDLs with the same call names.

Batch up halAppendCactus jobs in WDL

---

.gitlab-ci.yml
Dockerfile
Makefile
src/cactus/blast/cactus_blast.py
src/cactus/setup/cactus_align.py
test/evolverTest.py

[updating](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/updating-alignments.md) hal files often requires sequences be aligned to a pre-existing ancestor.  In `cactus` this is triggered simply by including the ancestral sequence in the input.  
But when running `cactus-prepare / cactus-blast / cactus-align` ancestral sequence entries get created as part of the workflow and they are ignored until they are needed.  So there is no way let them be used as an input.
This PR adds an `--includeRoot` override to do so in `cactus-blast` and `cactus-align`.  So running, ex, `cactus-blast ./jobstor seqs..txt Anc2.cigar --root Anc2 --includeRoot` will include Anc2 in the alignment (and throw an error if Anc2 is not in seqs.txt.
Todo; really need to get the update examples under …

Fix cactus-blast and cactus-align so they can be used for updating genomes

---

ReleaseNotes.md
src/cactus/shared/common.py

Since `cactus_consolidated` can take a long time, it's really helpful to get its stderr messages in real time.  Doing this in Toil took a [little hacking](https://github.com/ComparativeGenomicsToolkit/cactus/blob/465b4024a4581e82b31c97a781b5a50e68a92785/src/cactus/shared/common.py#L790-L798) where a child process is forked off to send realtimelogging messages as the main process runs.
But in Docker, this could sometimes cause Toil to [loop forever](https://github.com/ComparativeGenomicsToolkit/cactus/issues/610#issuecomment-1006125899).  And according to @adamnovak's [explanation](https://github.com/ComparativeGenomicsToolkit/cactus/issues/610#issuecomment-1015759593), this is because the init daemon inside docker doesn't, by default, clean out "zombie processes".
And apparently, exiting …

Fix endless loop after cactus_consolidated that happens in some --realTimeLogging / Docker combinations

---

reference/impl/addReferenceCoordinates.c

Improves #643 by moving up the `stSortedSet` toggle for caps and ends to apply to `setAdjacencyLengthsAndRecoverNewCapsAndBrokenAdjacencies()`  as well.  Didn't work the first time I tried because I had it before instead of after the `getCaps()` call in `bottomUp1()`

Speed up reference (again)

---

.gitmodules
Makefile
README.md
ReleaseNotes.md
src/cactus/blast/cactus_coverageTest.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/shared/common.py

Switch from [cPecanLastz](https://github.com/ComparativeGenomicsToolkit/cPecan/tree/master/externalTools/lastz-distrib-1.03.54) to newer version of [lastz](https://github.com/ComparativeGenomicsToolkit/lastz/commit/6114fb94ff14069c53605dc49e53d2f883e9f997).  This seems to solve the [error reported here](https://github.com/ComparativeGenomicsToolkit/cactus/issues/641#issuecomment-1020599920).  Which is why I'm fast-tracking this change into master now, even though it is already in the "paf-chains" branch. 
Also, prepare for a release.

Update to newer lastz

---

Dockerfile
README.md
src/cactus/shared/common.py

There is currently no way to specify which Docker binaries to use.  This PR adds an override option via `CACTUS_DOCKER_TAG` which could, for example, allow someone to use the GPU docker image (#651 is a possible use case).  I think it would be cleaner to eventually just detect that a GPU is wanted and automatically use the latest gpu release.
This also brings in a patch from #652 that lets the docker build work again in light of a trouble-making [new pip version](https://github.com/DataBiosphere/toil/issues/4028)

Add Docker Tag override

---

BIN-INSTALL.md
README.md

@ekinda reasonably [points out](https://github.com/ComparativeGenomicsToolkit/cactus/issues/447#issuecomment-1029153970) that the installation instructions can be confusing:  They describe adding `cactus/bin` to `PATH`, but don't mention that you have to do this each time you want to run cactus in a new shell.  Forgetting to do so will cause cactus to try to pull in a docker image for the binaries, and if that's not set up well, will lead to a confusing error message. 
This PR attempts to fix that by changing the instructions to update the virtualenv instead.  This way the PATH gets updated whenever the virtualenv is sourced, which I think is more intuitive.  
It also syncs up the instructions in README.md and BIN-INSTALL.md (which shuold be kept consistent), and specifies use of pip 21 …

Update python installation instructions

---

bar/impl/poaBarAligner.c

There's a bypass of `make_consistent_partial_order_alignments()` where if all the sequences start at the same end, it aligns them once from that end and that's it.  This seems reasonable enough, but #654 shows a case where this isn't working.  It seems it's aligning the same sequence to its reverse complement and another sequence.  Something somehow turns out off-by-one, and it folds a bunch of self loops up. 
But this doesn't happen when the consistency code is enabled for this case.  So this PR just turns on `make_consistent_partial_order_alignments()` for all non-trivial alignments.  On my test-case, this fixes the self-loop without affecting speed.  
This seems like a band-aid fix though.  Is the inconsistency itself due to an underlying off-by-1 bug?  Or is there away to be more …

Use consistent poa bar for all but trivial alignments

---

bar/impl/flowerAligner.c
bar/impl/poaBarAligner.c

This is a better solution courtesy of @benedictpaten  for the self-loop issue in #654 than was previously added via #655: instead the of the consistency bypass being disabled for all but trivial alignments, it is properly fixed to be disabled for only self-alignments.

Fix to poa-bar self-alignment bug.

---

bar/impl/poaBarAligner.c

This will get progressive mode working with the abpoa command line debug logic.

fix abpoa command dumper wrt -S -p opts; turn off sanity check

---

bar/tests/flowersShared.h

`gcc-10` and above [flipped](https://gcc.gnu.org/gcc-10/porting_to.html) a default from `-fcommon` to `-fno-common`, and as a result, gcc will reject multiple definitions of global variables. 
```
linuxbrew@295dcf1deec5:~/cactus$ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
ERROR using GCC 10:
```
make[4]: Entering directory '/home/linuxbrew/cactus/bar'
cc -Iinc -Iimpl -I../hal/inc -I../api/inc -I../setup/inc -I../bar/inc -I../caf/inc -I../hal/inc -I../reference/inc -I../pipeline/inc -I../submodules/sonLib/C/inc -I../blastLib -I../submodules/sonLib/externalTools/cutest …
```

gcc-10 and above flipped a default from -fcommon to -fno-common.

---

paf/paf_tile.c
src/cactus/blast/cactus_blast.py
src/cactus/paf/local_alignment.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_progressive.py
src/cactus/setup/cactus_align.py
src/cactus/shared/configWrapper.py

Some of the overrides remain a bit hacky.  (think we'll need a new comand line option equivalent to --consCores for running on aws/autoscale, for example).
Also, there may be a speed regression in some cases because alignment jobs are smaller than they were on master where everything was just cat'd together.  Don't think it should be too serious though.

Add back segalign support

---

README.md
paf/fasta_chunk.c
src/cactus/paf/local_alignment.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py

* Fix bug in `fasta_chunk` where `-c` was parsed as 32bit int (this value gets set to 6G for SegAlign). This bug was introduced recently in the change from `cactus_blast_chunkSequences` to `fasta_chunk`. 
* Use meaningful (EVENT_CHUNK) filenames for lastz input in order to make logging more informative. (protip @benedictpaten always run with `--realTimeLogging` in order to print all commands run as soon as they are run)
* Capture and parse segalign's stderr and double-check it for some keywords that could indicate failure as it still seems possible for it to fail but still exit 0. 
Resolves #694

More GPU integration

---

setup.py

Networkx version 2.81 (may 18th) breaks the outgroup test.  This rolls back the required version in setup.py to be < 2.8.1.  (todo: get Cactus working with latest networkx)
```
File "/builds/comparativegenomicstoolkit/cactus/src/cactus/progressive/outgroupTest.py", line 244, in testDynamicOutgroupsOnRandomTrees
og.compute(maxNumOutgroups=3)
File "/builds/comparativegenomicstoolkit/cactus/src/cactus/progressive/outgroup.py", line 314, in compute
self.__dpInit(node)
File "/builds/comparativegenomicstoolkit/cactus/src/cactus/progressive/outgroup.py", line 346, in __dpInit
self.dpTree = copy.deepcopy(self.mcTree)
File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
state = deepcopy(state, memo) …
```

Fix CI, which broke due to networkx update

---

Dockerfile.segalign
Makefile
build-tools/makeBinRelease

* apply hack to segalign dockerfile to work-around cuda docker image issue with apt key
* force lastz to build static in `makeBinRelease` script
* fix check-static Makefile rule that did not work due to using wrong kind of if.

Fix release scripts

---

BIN-INSTALL.md
README.md
build-tools/makeBinRelease

Switch from (very old) 2.7.2 to (very new) 2.9.12.
Resolves #742 and probably #688 and #585
I'm hoping the newer library is fixing some sort of quirk in the static build, and it's not just a case of either version working on some systems and not working on others.  But I only have [one datapoint](https://github.com/ComparativeGenomicsToolkit/cactus/issues/742#issuecomment-1172036016) to go on so far, so who knows -- will err on the side of the more up-to-date library.

Update libxml2 version used in static binaries build

---

doc/pangenome.md
preprocessor/Makefile
preprocessor/cactus_sanitizeFastaHeaders.c
src/cactus/blast/cactus_blast.py
src/cactus/paf/local_alignment.py
src/cactus/preprocessor/checkUniqueHeaders.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/cactus_terra_helper.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_refmap.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

Before, cactus would add `id=EVENT|` prefixes to fasta files in its setup phase.  This was annoying, but made sure downstream code worked (to an extent).  
paf_chains pushed this logic into the preprocessor which is simpler in some respects.  But can lead to terrible problems if the user didn't run `cactus-preprocess` (and has bitten me several times).
This PR adds back the check, but hopefully in a simpler and faster way.  After importing fasta files, a new tool `cactus_sanitizeFastaHeaders` gets run on them to immediately add prefixes if they are not already found.  As a bonus, it unzips gzipped files so those should be generally supported now too.

Add back automatic fasta header prefix logic

---

Dockerfile.segalign
build-tools/makeGpuDockerRelease
src/cactus/progressive/cactus_terra_helper.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py

Some other small things
* Fix up `cactus-terra-helper scrape-logs` to not take empty logs
* Add name-checker in pangenome tools to make sure that the reference sample name is not a prefix of another sample name (until `cactus-graphmap-join` doesn't rely on prefixes for path selection)

Make sure base docker images exactly consistent across build

---

README.md
src/cactus/shared/common.py

This prints out commands as they are executed: very valuable for debugging, and figuring out what's running when.  imho better on by default than off.

enable --realTimeLogging (whether user asks for it or not)

---

src/cactus/progressive/cactus_prepare.py

This makes it possible to run `halAppendSubtree` on large alignments

Update hal for patched halAppendSubtree

---

README.md
src/cactus/progressive/cactus_prepare.py

Resolves #792.
As mentioned in that issue, it'd be nice to one day find the time to automatically estimate it  from the input sequence size

fix terra disk rounding to only use acceptable multiples of 375

---

doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_minigraph.py

This simple heuristic seems to help Partial Order Alignment in general.  And seems better than using the arbitrary order that most seqfiles will be in. 
The user can override this by toggling `minigraphSortBySize` in the xml confiration.

Add biggest genomes first in minigraph construction

---

caf/impl/filtering.c

a debugging statement that got committed by accident

fix accidental return true

---

caf/impl/caf.c
src/cactus/setup/cactus_align.py

This was due to a simple 1-line merging bug that reset the same config variable twice, causing all overrides applied from the `--pangenome` option to be lost.  
The critical override was that disabling the megablock filter, something that only comes up on deeper datasets that those found in the CI tests. 
All credit for finding this terrible regression goes to @minglibio who [patiently](https://github.com/ComparativeGenomicsToolkit/cactus/issues/780#issuecomment-1241758004) and persistently [raised it with supporting data](https://github.com/ComparativeGenomicsToolkit/cactus/issues/780#issuecomment-1260958635)
Resolves #780

Fix --pangenome option regression from v2.2.0

---

caf/impl/caf.c
src/cactus/cactus_progressive_config.xml

Apparently when @benedictpaten changed the value of `minimumBlockDegreeToCheckSupport` from 10 to 0 in https://github.com/ComparativeGenomicsToolkit/cactus/commit/9cbbb9045a93166bc3d8b02b6d9209f19196f7bf it was with the intention of disabling the filter. 
But what it did in effect was apply the filter to all blocks, instead of those with degree > 10.  
This PR leaves the setting at 0, but changes the interpretation of 0 as a special toggle-off value.  
@benedictpaten should we run some tests for this?

turn off megablock filter when support set to 0

---

src/cactus/progressive/cactus_prepare.py

`--includeRoot` is used to tell `cactus-blast` and `cactus-align` that the sequence of their root ancestor (`--root`) is to be taken from an input fasta file.  This is necessary for various updating operations where, for example, we might want to glue one tree onto another using `halAppendSubtree --merge`.  
This PR updates `cactus-prepare` to accept this option too,  This makes it much easier, for example, to re-generate a subtree on Terra and have it be ready to glue into a bigger alignment.  
Todo: add support for the  `--root` option too

Add --includeRoot option to fix ancestor to cactus-prepare

---

Makefile
README.md
build-tools/downloadPhast
build-tools/makeBinRelease

We're already building and linking phast during the release builds in order to make `halPhyloP`.  This PR adds the various bins from the phast package (`phyloP, phyloFit, etc`) too for convenience of having access to them within the cactus docker (or with the bin install).

Copy phast binaries to bin/

---

src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/progressive_decomposition.py

@vpymerel raises a serious bug with the `--root` option when running `cactus` (in the wrong github) [here](https://github.com/glennhickey/progressiveCactus/issues/132)
Namely with this tree
```
(BGIGI:0.216097,(((TGE_A:0.00174569,TGE_H20:0.0018409):0.00325768,TPA:0.00711254):0.0110921,(((TCM:0.00370156,TSI:0.00335399):0.00562986,(TDI:0.00349392,TPS:0.0069705):0.00518438):0.0073258,(TCE:0.0131574,TMS:0.00461954):0.00878047):0.00799635)TIMEMA:0.186162);
```
it fails with this error when run with `--root TIMEMA`
```
File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 147, in progressive_schedule
raise RuntimeError("Unable to schedule job dependencies. Please file a bug report on github")
RuntimeError: Unable to schedule job dependencies. …
```

fix --root option

---

src/cactus/maf/cactus_hal2maf.py
src/cactus/preprocessor/dnabrnnMasking.py
src/cactus/preprocessor/fileMasking.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py
src/cactus/shared/configWrapper.py

Cactus uses toil's `cpu_count()` for some jobs, generally on singleMachine batch systems, to default to scheduling them using all available cores (note: this can always be lowered with `--maxCores` and some other more targeted options).  But apparently, this [overestimates the number of available cores in some environments](https://github.com/ComparativeGenomicsToolkit/cactus/issues/820).  So following advice from #820 we use `os.sched_getaffinity(0)` instead (reverting back to cpu_count() if that doesn't work).  Thanks @ericdeveaud and @adamnovak .  Resolves #820.  May make sense to apply this to Toil too in order to get better maxCores defaults...

Try os.sched_getaffinity(0) before toils cpu_count

---

.gitlab-ci.yml
Dockerfile
Makefile
build-tools/downloadMafTools
build-tools/makeBinRelease

I also wanted to refactor to download TAF the same way while still running the TAF tests, but ran into a [cryptic error](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/26714) that'll have to be dealt with some other time.

Include maftools in bin/ via downloadMafTools

---

src/cactus/shared/common.py

This will hopefully fix #748 where we suspect caching is behind weird Toil errors.

disable caching for slurm/lsf/torque

---

build-tools/downloadPangenomeTools
doc/mc-pangenomes/README.md
doc/pangenome.md
doc/progressive.md
examples/yeastPangenome.txt
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/setup/cactus_align.py
test/evolverTest.py

Stacks on #831 (to me merged first)
Right now, the recommended recipe is to run `cactus-graphmap-join` three times to make the `full`, `clipped` and `frequency-filtered` graphs.  This is mentioned in the larger examples, but still pretty confusing and error-prone.  It's also really easy to end up with giraffe indexes that don't work well. Or try to make a distance index with an unclipped graph and run out of memory.  Or do no clipping because it wasn't mentioned in the quick start, etc. 
Anyway, this PR attempts to streamline things
* all three graphs are made with a single invocation of `cactus-graphmap-join`
* there are sensible defaults (vcf from the clipped graph, giraffe indexes from a "d2" filtered graph)
* some cli options are moved into the config (ie gfaffix is on by default …

[WIP] Redo cactus-graphmap-join's interface

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/setup/cactus_align.py
test/evolverTest.py

* Use vg's new [path metadata](https://github.com/vgteam/libhandlegraph/blob/a9e33664ab73a3751f139bc4a7d07098de9e8515/src/include/handlegraph/path_metadata.hpp) interface where possible
* Output GBZ instead of XG/GBWT
* Output GFAs will no longer have P-lines
* Hacky `--wlineSep` option no longer needed
* No more input naming conventions required except for ".1/.2" sample names for diploid samples (ie don't need to add .0 to haploid non-reference samples anymore)
None of this can be put into a cactus release until [GBZ performance issues](https://github.com/vgteam/libbdsg/issues/168) are dealt with.

[WIP] Pull in latest vg

---

build-tools/downloadPangenomeTools

Updates to latest minigraph.  This minigraph version should fix the `l == gc->qe - gc->qs && gc->p->aplen == gc->pe - gc->ps` [assertion error](https://github.com/lh3/minigraph/issues/76) that's come up in a couple issues here:
Resolves #800
Resolves #832

Update minigraph to v0.20

---

src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py

This lets you tell which genome a given lastz-repeatmasking command is being run on.  
This is especially useful for `segalign_repeat_masker` as it still has trouble with some inputs (crashes and/or giant runtimes), and it's nice to be able to figure out which input genome it's failing on just by looking at the logs.

Readable temp filenames for preprocessor repeatmasking

---

Makefile
README.md
build-tools/downloadPangenomeTools
doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_minigraph.py

Previously, it was using genome size.  But this was giving pretty counterintuitive results when making a pangenome of different species.  
So now genomes are now added in order of how close they are to the reference as determined by `mash dist`. 
This can be toggled in the config using the `minigraphSortInput` attribute.  It's set to "mash" by default, but can be changed to "size" to go back to using size.  Any other value, ex "0", will just use the ordering from the seqfile.

Use mash distance to determine minigraph construction order

---

src/cactus/update/cactus_update_prepare.py

Fixing issue #753 
After the fix,
```bash
python3 cactus_update_prepare.py add                                                                                                                                                                                                                      
usage: cactus_update_prepare.py {add,replace} [-h] [Options] add [-h] {node,branch} ...
positional arguments:
{node,branch}  Methods to add a new genome
node         Adding a new genome to a node (aka, the adding-to-a-node approach)
branch       Adding a new genome to a branch (aka, the adding-to-a-branch approach)
optional arguments:
-h, --help     show this help message and exit
```
also
```bash
python3 cactus_update_prepare.py add node …
```

fixing empty 'add' parameter during the call of 'cactus_update_prepare'

---

bar/impl/poaBarAligner.c
build-tools/makeBinRelease

Now that [this bug](https://github.com/yangao07/abPOA/issues/26) is fixed, abPOA should work reliably with sse4.1 instructions.  
I was going to enable them by default, but the test data in that issue above is still almost 50% slower on sse4.1 than avx2 (on same machine).  So will keep using avx2 by default, but enable abPOA via sse4.1 in the "legacy" binaries.  And future releases will have minigraph-cactus support in these legacy binaries (whereas before it was just progressive cactus w/ pecan).

update abpoa and enable it in legacy binaries

---

src/cactus/setup/cactus_align.py

This is really important for getting rid of false alignments in the HPRC data, but it somehow got deactivated in the big v2.2.0 merge.  Terrible that it took this long to notice.

Add back pangenome paf_filter

---

api/tests/cactusParamsTest.c
src/cactus/cactus_progressive_config.xml
test/evolverTest.py

Cactus alignments are too fragmented.  The existing chain length filters, `annealingRouds` and `deannealingRounds` in `<caf>` can drastically improve this, but at a cost to sensitivity. 
One of the main issues is the [evolver](https://doi.org/10.1101%2Fgr.174920.114) test [data](https://github.com/UCSantaCruzComputationalGenomicsLab/cactusTestData/tree/master/evolver/mammals/loci1), which has been used to tune Cactus pretty much since day one and still features heavily in our CI tests.  
This data seems to be enriched for very small duplication-type events. Also, the maf comparison used is column based and won't penalize giant rearrangements much if they feature teeny tiny blocks.  
The result is that the current default chain filtering parameters favour such alignments.  For example, …

[WIP]: Fix chaining

---

src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py

When trying to clean up the lastz repeatmasking logs to make them easier to debug (#852) I managed to break gpu repeatmasking (#881).  Which is ironic as the whole point was for debugging gpu repeatmasking crashes...   Anyway, even a tiny GPU being available for CI testing would go a long way (perhaps when we get the new cluster). 
Resolves #881

Fix temp file path issue with gpu repeatmasking

---

src/cactus/blast/cactus_blast.py
src/cactus/cactus_progressive_config.xml
src/cactus/paf/local_alignment.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/common.py
src/cactus/shared/configWrapper.py
toil-requirement.txt

@adamnovak added the `accelerators` resource to Toil, which allows setting the number of GPUs in each job.  This is vital for getting Cactus with GPU to work on AWS (as it allows dividing cpu and gpu jobs between appropriate instance types).  
This PR updates Cactus to use `accelerators` for jobs that run Segalign.  It does so via the new `--gpuCount` option (and also `gpuCount` properties in the config).  By default, the current functionality is kept: all gpus are used by each segalign job (regardless of what toil thinks) if `--gpu` (or `gpuLastz`) are toggled on.  But the `gpuCount` can be used to finetune things if desired.  
For this to be usable on AWS, [Toil needs to be able to run gpu docker images](https://github.com/DataBiosphere/toil/issues/4282).
Also, [we cannot specify the …

[Do not merge yet] Incorporate Toil GPU support

---

Dockerfile

Something messed up bgzip in the docker image.  Probably related to the apt install of libhts-dev for taffy.  This is probably a warning sign that the docker and static build scripts may need a little revision, but adding libdeflate to the runtime seems to fix it for now.

Try to fix linking in dockerfile

---

.gitlab-ci.yml
.gitmodules
Dockerfile
Makefile
build-tools/downloadMafTools
build-tools/makeGpuDockerRelease

Was having problems with the release script (and Dockerfile #886).  To simplify things a bit, this PR moves taffy out of submodules and into the maf tools downloader script.  From there is builds against its own htslib to (hopefully) avoid weird conflicts down the road.

Rejig taffy build

---

src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/progressive_decomposition.py
src/cactus/progressive/seqFile.py

I just got burned by a typo in a species name in the input tree.  Running via cactus-prepare/cactus-blast/cactus-align this would be a fatal error.  But with just cactus, it just silently forgets about the species and keeps on going.  This is apparently [intentional](https://github.com/ComparativeGenomicsToolkit/cactus/blob/2b2918de27e9cc585f2bc87df79574e269d1adfc/src/cactus/progressive/seqFile.py#L172-L199).
This PR changes things so that only species outside the given root behave this way, and that the message goes through the logger.

Better tree name checking in cactus

---

build-tools/makeGpuDockerRelease
doc/progressive.md
src/cactus/blast/cactus_blast.py
src/cactus/cactus_progressive_config.xml
src/cactus/paf/local_alignment.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/configWrapper.py

We used to have the `--gpu` option that toggled on gpus.  Then I added `--gpuCount` in #844 when testing out Toil's new accelerators resource.  But I don't think we really need the two separate options going forward, so before the next reelase this PR gets rid of `--gpuCount`.  The logic is now
* `--gpu`: toggle on segalign and give it all available gpus (same logic as always)
* `--gpu N`: toggle on segalign and give it `N` gpus (required when not using single machine)
* `--gpu 0` or don't specify `--gpu`: use lastz instead of segalign. 
The GPU enabled docker releases will keep having `--gpu` set by default (ie using all available GPUs unless otherwise set).

Get rid of --gpuCount option

---

src/cactus/maf/cactus_hal2maf.py

This option is slow and has been shown to give unexpected results on some large data sets.  So remove it from `cactus-hal2maf` to avoid getting anyone's hopes up.  Keeping in mind that the same functionality is getting performed by the taffy normalization (50bp by default, controllable by the `--gapFill` option).

remove --maxRefGap option from cactus-hal2maf

---

.gitlab-ci.yml
Dockerfile
build-tools/downloadMafTools
build-tools/makeBinRelease

Enable htslib in taffy included in Cactus, allowing bgzip support.  This should have been on before, but wasn't due to a bug.

Fix taffy / htslib issue

---

BIN-INSTALL.md
README.md
doc/pangenome.md
doc/progressive.md
setup.py

Toil (and therefore Cactus) requires python >= 3.7. Something I've recently forgotten [forgetten](https://github.com/ComparativeGenomicsToolkit/cactus/issues/897#issuecomment-1378598668) when trying to help people with issues stemming from [being on python 3.6](https://github.com/DataBiosphere/toil/issues/4315#issuecomment-1416381653).
This PR adds a few more mentions in the docs...

More visibility for python 3.7 requirement. 

---

build-tools/downloadPangenomeTools

There's a recent(ish) bug in `vg clip` that can crash on the last edge of a path.  This was brought to light here: #920. 
This PR switches to a custom-built vg that has a patch for this.

Update to patched vg for vg clip fix

---

build-tools/downloadPangenomeTools
doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

This forces everything to be a bubble. If something is dangling (and it's not the beginning of a ref chromosome) after graphmap and align, it gets clipped out by default now in join. 
We could soften this to allow dangling nodes from minigraph, but I don't think it would make a difference since minigraph doesn't produce them either (I think). 
The rationale is that the dangling nodes are probably not helping any current applications. And by mucking up the snarl structure, they are potentially making things like indexing more difficult than need be. 
The old logic, where stubs are kept, can be activated by toggling off `removeStubs` in the config.

remove stubs (by default) in pg clipping

---

build-tools/downloadPangenomeTools
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py

`vg deconstruct` won't use GFA (unchopped) node ids in the VCF by default anymore as of https://github.com/vgteam/vg/pull/3879.  
This PR adapts minigraph-cactus toggle this on by default (being consistent with how `cactus-graphmap-join` has always worked).  It can now be disabled in the config via `GFANodeIDsInVCF`.  
As mentioned in https://github.com/vgteam/vg/issues/3873, it may just be simplest to pre-chop everything to have a gfa consistent with the vg indexes.  This could at the very least be an option..

Adapt to newest deconstruct interface

---

src/cactus/blast/cactus_blast.py

These --restart bugs find there way into the code during refactors and big merges because the CI tests can't check for them.  Thanks #960 for flagging this one.

fix cactus-blast --restart

---

src/cactus/cactus_progressive_config.xml

We've been seeing alignments across stretches of Ns in pangenome alignments (ex #859). I noticed first noticed this when making a test mouse pangenome (https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=publications/mc_2022/mc_pangenomes/30-mouse-mc-2022-09-23). 
It's also come up when visualizing MAFs from Progressive Cactus. 
Anyway, finally looking at it now, and it seems a fairly simple issue with the abPOA scoring matrix we're using:
```
91 -114 -61 -123 0
-114 100 -125 -61 0
-61 -125 100 -114 0
-123 -61 -114 91 0
0 0 0 0 0
```
The last row/column is for N, and they are being treated as ambiguous bases that can align to anything.  This makes sense in and of itself, but for most assemblies coming into Cactus, Ns are gaps and aligning too them only serves to …

Penalize N mismatches in abPOA

---

BIN-INSTALL.md
Dockerfile
build-tools/downloadMafTools
doc/progressive.md
setup.py
src/cactus/maf/cactus_hal2chains.py
src/cactus/maf/cactus_hal2maf.py
src/cactus/maf/cactus_maf2bigmaf.py

This is a stand-alone Toil script to convert a HAL file to a set of pairwise alignments in [UCSC Chain Format](https://genome.ucsc.edu/goldenPath/help/chain.html).
I copied some [logic I found in CAT](https://github.com/ComparativeGenomicsToolkit/Comparative-Annotation-Toolkit/blob/fc1623da5df1309d2e2f0b9bb0363aaab84708f4/cat/chaining.py#L96-L98):
```
cmd = [['halLiftover', '--outPSL', hal, args.ref_genome, bed_path, target_genome, '/dev/stdout'],
['pslPosTarget', '/dev/stdin', '/dev/stdout'],
['axtChain', '-psl', '-verbose=0', '-linearGap=medium', '/dev/stdin', target_two_bit, query_two_bit, chain]]
```
I have never personally created nor used Chain output before, so would appreciate feedback by people who have @diekhans @mhaukness-ucsc
Also, I've noticed there are two ways to make PSL …

cactus-hal2chains

---

doc/progressive.md
src/cactus/maf/cactus_hal2maf.py

Despite working pretty well on a lot of data, this option does not seem ready for prime time, leading to segafults, for example, on a giant chrY maf.  
This PR turns it back off by default.  Once it's fixed it can go on by default with `--dupeMode single`.

Toggle taffy norm dupe filter off by default

---

src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py
src/cactus/setup/cactus_align.py

This fixes a bug where ".<haplotype>" suffixes on reference sample names would lead to errors in `cactus-graphmap-join` due to the various conversions in vg. 
It also adds better error checking up front make sure that if you have a "." in a sample name, then it won't lead to any trouble downstream.
A sample name is valid now if it either contains no `.` or if its last `.` is followed by an integer. 
Anyone using `Cactus <= v2.5.0` should keep all `.`'s out of their reference sample names. 
Resolves #993

More robust handling of dots in sample names

---

build-tools/downloadPangenomeTools

This fixes issue where `.dist` indexes output with `--giraffe` could be extremely slow to map to for complex graphs.

switch over to patched vg

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py
test/evolverTest.py

`cactus-pangenome` changed to accept multiple samples via `--reference`.  Only the first one is treated as a true reference (left unclipped and guaranteed forward and acyclic), but the others will end up as REFERENCE sense paths in the final GBZ graph.  This makes it easier to use them for indexed coordinates.  
All such paths can be optionally used to make VCFs via the `--vcfReference` option (one VCF per reference).  Because of potential cycles, these VCFs will not be as accurate and VCFs on the first reference, but they should still be quite good.

fix up multiple reference sample support

---

src/cactus/refmap/cactus_graphmap_join.py

Some stats files made by clipping get exported from Toil at the end of the worfklow.  The problem is that it would crash if they don't exist (!).  The work-around is to always make a `clip` graph, but this patch will fix it properly.  Crazy that it took this long for this to get noticed...
resolves #1005

Fix crash during export when no clip graph produced

---

src/cactus/shared/common.py

There seems to be two issues in error handling from failed `cactus_call` invocations: 
1) stdout was being included in the error message, which would barf with non-ascii characters (ie when file being created was binary which happens for every `vg` command)
2) vg actually started to [put non-ascii characters in its own crash error messages](e0bb8540c49011ca38d102e26870eb4e14d1a18a) for some reason 
The result is that when vg crashes, it causes cactus to crash while handling the error leaving a very confusing message like `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 257: ordinal not in range(128)` as happened in #1001.
This PR switches from `ascii` decoding for `cactus_call` to decoding with the default locale while parsing stdout and stderr, which seems to fix …

stop using ascii decoding

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

Previously, running `cactus-pangenome` with something like `--gfa filter` would lead to a crash, since the `clip` graph on which the `filter` graph depends wouldn't be created.  This fixes that by making sure that all dependencies are produced as necessary.

Fix error when filter specified without clip

---

src/cactus/refmap/cactus_graphmap_split.py

By default, `cactus-graphmap-split` will make a subproblem for each contig in the reference genome.  This can become clunky for tiny contigs like unplaced scaffolds etc, so it is recommended to manually specify the chromosomes with `--refContigs` and, if you want to keep the rest, through it into one job with `--otherContig chrOther`. 
But in some cases, not specifying these options can lead to a really cryptic crash, where nothing reliably maps to a given reference contig (not even itself) and it ends up in a kind of empty job that trips out downstream assertions.  
This PR explicitly checks for these cases and filters them out (so these contigs will *not* make it into the final graph).  
I think there's room for improvement here with a simpler interface that can automatically detect …

Automatically filter out "empty" chromosome jobs

---

doc/pangenome.md
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py

* add new `--mgCores` option (default all cores) to specify cores for minigraph construction
* `--mapCores` is kept as is but now only applies to `minigraph` mapping
* documentation fixed to reflect fact that `--indexCores` does not, in fact, default to 1
* `--indexCores` changed from defaulting to all available to all available minus 1
At the end of the day, this should lead to more useful default behaviour of `cactus-pangenome` on single machine.

clean up pangenome cores options a bit

---

build-tools/downloadMafTools
src/cactus/pipeline/cactus_workflow.py
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/common.py

Added this option to get something working, but clearly did not properly test it.  There were two major bugs:
* was interpreted as Kb and not Gb as the help message said
* it was only activated when running `cactus-align` and not `cactus`
This PR should fix both issues.  The interface is changed to be more like Toil's usual memory options.  So it's read as bytes, but you can use `Gb` `Ki` etc to specify different units.  
I do hope to have better resource estimation in before the next release to make this option (which still needs documentation in the manual) more rarely needed.

Fix --consMemory option

---

src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/progressive_decomposition.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/setup/cactus_align.py
src/cactus/shared/configWrapper.py

Users aren't asked for an input tree when making pangenomes, but under the hood a star tree is used.  This default tree uses the default branch lengths, which have always been "1" in cactus.  
But now that branch lengths affect chaining, we probably want to make sure they're more sensible for pangenomes.  This PR moves default branch length specification into the config.xml, where two values are kept, one for progressive (which remains 1), and one for pangenome which is 0.025 (which is what cactus-align used to hardcode it to).

Shorter default branch length in pangenome mode

---

src/cactus/refmap/cactus_graphmap_join.py

There are two issues here.
1) A bug where the "tab" character got replaced by spaces in the python source which left `_MINIGRAPH_` paths in the GFA (and all following indexes)
2) An old assumption that the chromosomal output of `cactus-graphmap-join` might be used by subsequent calls thereof -- something that's not really encouraged in the new interface. 
So this PR fixes the grep, and explicitly drops the paths from the chromosomal vg.  The result is that `_MINIGRAPH_` should no longer appear in any of the "full" outputs anymore.

Drop _MINIGRAPH_ paths from final output

---

doc/pangenome.md
src/cactus/refmap/cactus_graphmap_join.py

This option will chop all nodes to 1024bp very early on.  This way, all output graphs will be in consistent id space. 
By default (if this option is not used), then the graphs are left unchopped, but gbz constructiont will do its own chopping, meaning that there are two node spaces: one for gbz and everything derived from it, and one for everything else.  Which can make debugging maddening (the translation is kept in the GBZ and automatically used by some vg tools, but this sadly usually only adds confusions).

add chop option for pangenomes

---

src/cactus/refmap/cactus_pangenome.py

When running `cactus-pangenome`, the chromosomes are apparently joined together in arbitrary order.  This PR changes it to sort by chromosome name.  This way chr1 will have id 1, and appear first in the GFA file.  (no impact on anything else I can think of apart from id names and gfa line order).

Fix chrom ordering in cactus-pangenome

---

doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_split.py

Having a graph file for each unplaced contig in the reference is annoying.  But specifying the reference contig names you want to keep is also annoying.  The current logic uses a size threshold (anything >10% max contig length gets its own file).  But even on human this doesn't work great because chrM gets lumped in with all the other stuff, whereas it's nice to have a chrM.gfa/vg in the chromosomal output. 
This PR adds a name regex option the the logic, that can be used to override the size parameter.  It defaults to chrXXX, which covers most of the ucsc assemblies I've been using.  It's not going to work everywhere, and people are probably still best taking the time to set it by hand, but will help for a lot of test cases.

Better refcontigs autodetect

---

build-tools/downloadMafTools
doc/progressive.md
src/cactus/maf/cactus_hal2maf.py

As discussed in #1063, there's an existing tool, `maf_stream` that can squish together duplication rows in the MAF, without losing any coverage.  
This was an issue that just came up for me when looking at another alignment : multiple copies not allowed, but filtering them out visibly tanks coverage.  
The solution here kind of cheats in that the rows in the consensus MAF don't actually correspond the the fasta.  But PhastCons only considers the columns, so that should be okay. 
The interface for this is `cactus-hal2maf --dupeMode consensus`. 
Resolves #1063

add maf_stream consensus duplication filter, and recommend it for phast

---

build-tools/downloadPangenomeTools

It turns out the flags coming in from `makeBinRelase` into `downloadPangenomeTools` were mucking up odgi -- fixed by just unsetting them during build.

fix static release build

---

src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_pangenome.py

The `--refContigs` option is shared by `cactus-pangenome` and `cactus-graphmap-split`.  But during a recent refactor, it apparently stopped working in the latter, which is under a bit lest testing.  No matter what you gave to `cactus-graphmap-split --refContigs`, it would assume the option was empty and determine its own reference contigs.  The same option in `cactus-pangenome` worked fine, however.
Anyway, this PR should fix this issue.  And is probably worth a patch release once it passes its tests. 
Resolves #1078

fix --refContigs in cactus-graphmap-split

---

src/cactus/refmap/cactus_graphmap_join.py

The idea of the stub removal is to only have two stubs per chromosome in the output graph, which helps with snarl decomposition among other things. 
But as it stands, if there are multiple references, they are all allowed to make stubs.  This is defensible -- maybe these stubs will be of use when surjecting?  But I think for now we want to err on the side of simpler topology, so will treat stubs like the rest of the clipping -- only the first reference is exempt.

only allow stubs from first reference

---

build-tools/downloadMafTools
src/cactus/maf/cactus_hal2maf.py
test/evolverTest.py

I didn't realize it, but `maf_stream` re-orders the rows in the maf blocks.  This is bad news for, say, `taffy index`, which assumes the reference is the first row.  
this PR uses `mafRowOrderer` to re-sort the output of `maf_stream`.

Fix maf row order with --dupeMode consensus

---

src/cactus/refmap/cactus_minigraph.py
src/cactus/setup/cactus_align.py

There are components with no CHM13 contig aligned, but that shouldn't be a fatal erro when running with `--reference GRC3h8 CHM13`

Fix error check that trips up GRCh38 graph with second reference

---

ReleaseNotes.md
doc/progressive.md
setup.py
src/cactus/shared/common.py

Another tiny release, in an attempt to get something to pin a (GRCh38-based) hprc graph to.

prep release 2.6.4

---

src/cactus/progressive/multiCactusTree.py
src/cactus/progressive/seqFile.py

It's come up a few times that weird ancestor names in the input tree lead to very cryptic crashes late in the pipeline.  This PR adds a check to clean out any numeric names (which tend to be bootstrap or other kinds of confidence scores from phylogeny progreams) or duplicate names with a warning. 
Resolves #1107

ignore numeric and duplicate ancestor labels

---

build-tools/downloadPangenomeTools

This puts reference paths back into the SAMPLE#CONTIG format (as used by the v1.1 graphs).  They will continue to never work with vg v1.50.0 but that has now been fixed in 1.50.1.

Revert back to SAMPLE#REFERENCE

---

src/cactus/refmap/cactus_graphmap_split.py

`cactus-graphmap-split` uses `awk` at some point to [make a contig size table](https://github.com/ComparativeGenomicsToolkit/cactus/blob/022e7fbbf73f717f85586c97ceedb64beb0119f5/src/cactus/refmap/cactus_graphmap_split.py#L508-L512).
The problem is that some versions of `awk`, including the one in the cactus docker image (`mawk`) return scientific notation for numbers > 2Gb (32bits), and this trips up Cactus which casts it to int.  
This PR is a little patch that specifies float output, which seems consistent across `awk` flavours and number sizes and returns output readable by the existing code. 
In no way does this mean that `cactus-pangenome` will now work well on giant genomes... it's just this one particular crash that should be fixed. 
Resolves #1125

Fix awk arithmatic issue due to large contig sizes

---

src/cactus/refmap/cactus_minigraph.py

Noticed this when seeing counterintuitive minigraph ordering for flys.  What happened is that genomes named `A1, A2, A3` etc were being lumped together in the same sample while computing the mash distance, which skewed the final order.  This traced back to a python bug where the last character was getting dropped from comparison, which is fixed here. 
This bug only affects minigraph construction ordering when sample names have no '.' characters and more than one sample has the same name when the last character is dropped.

fix off-by-1 error in sample name extraction

---

doc/mc-pangenomes/16-fly-pg-2023-08-23-commands.md
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_minigraph.py

Rerunning the 16-fly pangenome on slurm failed completely due to some memory underestimates.  This PR makes some adjustments based on the following logging information
```
grep WARNING 16-fly-pg-2023-08-23.stderr
[2023-08-23T13:32:47-0700] [MainThread] [I] [toil-rt] 2023-08-23 13:32:47.958235: Successfully ran [minigraph]: "bash -c 'set -eo pipefail && minigraph -c -xggs -t 64 dm6.fa AB8.0.fa B7.0.fa A3.0.fa B6.0.fa OreR.0.fa A5.0.fa A1.0.fa B2.0.fa B4.0.fa A4.0.fa A6.0.fa B3.0.fa A2.0.fa B1.0.fa A7.0.fa | bgzip --threads 64'" in 18105.9872 seconds and 16.4 Gi memory with job-memory 9.3 Gi. Percent utilization: 177.2 **WARNING: limit exceeded**
[2023-08-23T14:06:21-0700] [MainThread] [I] [toil-rt] 2023-08-23 14:06:21.446413: Successfully ran: "bash -c 'set -eo pipefail && minigraph …
```

boost some job memory specs in light of 16-fly logging

---

src/cactus/refmap/cactus_minigraph.py

I've only used minigraph-cactus on data with well under 1% divergence (as measured by `mash dist`).
If you go much beyond that, things will generally run but stuff like losing contigs in chrom assignment, running out of memory, producing unusable graphs etc becomes much more likely. 
This PR just adds a warning (which will be buried in the log) if a mash dist > 0.02 turns up.

Add warning message for big mash dist

---

setup/impl/setup.c

Gets rid of messages like 
```
cactus_consolidated(chr2): The file /data/tmp/9eeeec3d467250f1999ba98b3759d207/6b90/9563/tmp4b8_vsdf/CHM13.fa is specified incomplete, the sequences will not be attached
```
(probably should just deprecate the whole function at some point?)

move 'will not be attached' message to debug

---

.gitlab-ci.yml
build-tools/makeCpuDockerRelease

#1176 stopped pushing a quay image for every single CI build.  But its attempt to only push release images was a bit ill thought out, in that it relies on a tag that may not be specified yet before the CI is run. 
I think there's room to fix this up better to get both cpu and gpu release built automatically directly on quay.  In the meantime, this PR moves the quay docker build out of CI entirely, and into a local script that gets manually run when making the release (exactly as has always been done for the gpu images).

move quay docker build out of ci into release script (as done for gpu)

---

src/cactus/blast/cactus_blast.py
src/cactus/maf/cactus_hal2chains.py
src/cactus/maf/cactus_hal2maf.py
src/cactus/maf/cactus_maf2bigmaf.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/outgroup.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py
src/cactus/refmap/cactus_refmap.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py
src/cactus/shared/configWrapper.py

This PR fixes a bug where `run_segalign_repeatmasker` was only getting 4G, which is a show stopper on slurm for anything but tiny genomes.
It also adds a hack so that `--defaultMemory` gets boosted to `4Gi` by default if docker/singularity binaries are specified.  Likewise, the `littleMemory`, `mediumMemory` etc values in the config.xml get increased to `4Gi` for docker/singularity.  This will hopefully address issues where tiny jobs just quietly disappear at random without anything helpful in the log (because, in part, I think, they don't trip a cactus_call exception)
What this PR **Does Not Do** (at least as I write this) is boost the memory of jobs that request their own memory on the input data sizes.  That means that running evolverMammals on the cluster will still work badly, …

Boost memory requirements to make docker binaries with slurm more stable

---

build-tools/downloadPangenomeTools

Previously, reference contigs would get names like `GRCh38#chr1` in .vg output files from minigraph cactus.  These would get changed to `GRCh38#0#chr1` after roundtrips through GBZ (ie in the whole genome indexes) which would be a confusing inconsistency. 
This PR rolls back `hal2vg` to the previous version, which will effectively use `GRCh38#0#chr1` everywhere.  This is more consistent and in line with PanSN conventions.  
(there is a bit of irony here as `vg` has just added support for undefined haplotypes in GBZ, which is great, but probably best to stick with hap==0 everywhere rather than hap==undefined everwhere which would lead to ugly W-lines with size_t(-1) values.)

Set HAPLOTYPE=0 by default for ref contigs in chromosome graphs

---

README.md
build-tools/makeCpuDockerRelease
doc/progressive.md
src/cactus/progressive/cactus_prepare.py
src/cactus/shared/common.py
src/cactus/shared/configWrapper.py

When switching CI recently, I stopped it from spamming quay.io with a Cactus image for every single commit.   This means that `--binariesMode docker` will no longer work by default, since it will look for a commit-tagged image that isn't there.  
This PR switches `--binariesMode` to default to the current release (which has been manually tracked in `common.py` for some time).  This is how prepare has worked on Terra.  
It also fixes `--binariesMode` to automatically switch to the GPU release as needed. 
The usual environment variables, `CACTUS_DOCKER_ORG`, `CACTUS_DOCKER_TAG`, can still be used to override the image.  The `--latest` option will still work, only it will point to the latest release rather than the latest commit.  
If someone really wants to test a non-released commit with …

default to latest release in --binariesMode docker

---

src/cactus/refmap/cactus_minigraph.py

samples are sent into minigraph in mash distance to reference order by default.  There's logic in there to keep different haplotypes of the same sample together.  But this logic breaks down in the event that the mash distance of two different samples is the same.  Even though it's 9 decimal places, this happens
```
HG00673.2 (size = 3053585067) to reference GRCh38 = 0.00075568 sample distance = 0.000805673
HG00733.2 (size = 3026533161) to reference GRCh38 = 0.00075568 sample distance = 0.000805673
```
which leads to `HG00673.2.fa HG00733.2.fa HG00733.1.fa HG00673.1.fa` which is what it's supposed to avoid. 
This PR will fall back to lexicographical order in case of sample distance tie.

keep sample haps together in event of mash ties

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py

Just noticed a regression as of a result of a refactor a few versions back. 
The issue is that some tiny reference contigs (such as found in the unplaced / random GRCh38 stuff) do not map back to the graph in the minigraph mapping stage.  For contigs that don't map at all, `cactus-graphmap` is able to detect then fill them in. 
But for contigs that map poorly enough to get filtered out by, say the MAPQ filter, those are now left in after `cactus-graphmap` (the refactor pushed the filter downstream to make playing with it easier with respect to not having to rerun the mapping).  The problem is that if a downstream filter removes all their mappings, they can end up excluded from the graph.  
This PR changes `cactus-graphmap-split` to make sure that reference contigs always get put into …

rescue tiny reference contigs from paf filter

---

src/cactus/refmap/cactus_minigraph.py

#1208 merged in a debug assertion that completely breaks support for diploid samples in pangenomes, and is a sign that we need a CI test for this..

remove assert False

---

src/cactus/progressive/cactus_progressive.py
src/cactus/setup/cactus_align.py

I recently changed `--consMemory` to override the memory specification for `hal2vg` as well as `halAppendCactusSubtree`, in addition to `cactus_consolidated`.  
But it seems that in doing so, I broke the automatic estimation when `--consMemory` isn't used.  The net effect is that these jobs would get the default-memory (`2G`) no matter what if nothing was specified with `--consMemory`.  
This PR should correct this by adding a separate memory override option to these functions.  The initial bug was because toil's `memory` option was being used before, but I was checking it *after* it was getting filled in with its default value.

fix hal/vg export --consMemory overrides

---

src/cactus/refmap/cactus_graphmap_join.py

I have a bad habit of confusing `*`s like in bash with actual regexes.  This lead to a longstanding bug in the `gfaffix` invocation that would potentially select more than the reference paths for `--dont_collapse`.  Since it only ever checks that the reference path didn't get collapsed, this went unnoticed until I publicly humiliated [myself](https://github.com/marschall-lab/GFAffix/issues/14). 
I don't think this bug would have too detrimental of an effect on most graphs -- it would just prevent collapsing of a duplication that otherwise would be zipped in certain very specific circumstances where all characters in the reference sample appear in another path name.

fix gfaffix dont_collapse regex

---

src/cactus/paf/local_alignment.py

This will hopefully fix the double-delete error described in https://github.com/DataBiosphere/toil/issues/4671 (which, for whatever it's worth, I can't seem to reproduce on aws, slurm, or single machine)

remove os.remove before deleteGlobalFile

---

doc/pangenome.md
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py

The minigraph construction memory estimate is way too conservative.  Ex it wants 400Gi for 6 human haplotypes.  This makes sense for noisy R9 assemblies but is 4X more than needed for HPRC assemblies. 
This PR cuts the memory requirement in half (almost) and adds a `--mgMemory` override option.

Lower defautl minigraph construct memory; add override option

---

src/cactus/refmap/cactus_pangenome.py

Fixes an issue with #1235 where a file could be imported and exported in parallel, leading to random failures expecially on larger data.

Fix job dependency bug in cactus-pangenome --noSplit

---

doc/pangenome.md
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

Way back when, I switched from outputting `xg/gbwt` to `gbz`, in order to keep consistent with `vg giraffe`'s interface. 
But there's been a number of times recently where I've wanted an `xg` (with all paths) for debugging with `vg chunk` and `vg find`.  So this PR adds an `--xg` option to output a whole-genome xg with all paths, as converted from the `.gbz` (ie with chopped nodes). It only works in conjunction with `--gbz`.

Add back --xg option to the pangenome pipeline

---

.gitmodules

The comparativegenomicstoolkit fork hasn't had anything cactus-specific in it for a while.  So this PR moves the submodule to directly use the upstream abPOA in order to make it easier to keep up with new releases.  Also update to latest release (v.1.4.3)

track upstream abpoa directly; update to latest release

---

doc/progressive.md
src/cactus/blast/cactus_blast.py
src/cactus/cactus_progressive_config.xml
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/outgroup.py
src/cactus/progressive/outgroupTest.py
src/cactus/progressive/progressive_decomposition.py
src/cactus/refmap/cactus_pangenome.py
src/cactus/setup/cactus_align.py
src/cactus/shared/configWrapper.py
test/evolverTest.py

This PR adds the `--chromInfo` option which allows the user to pass a map of genomes to sex chromosomes.  This information is used to choose outgroups that best cover the set of sex chromosomes in the ingroups, and will (by default) allow extra outgroups be selected as necessary to do this.  The idea is to prevent cases where, when aligning a male (XY) and female sample (X) chooses two female outgroups, which could result in a loss of Y in the reconstructed ancestor.  
It also adds a `--maxOutgroups` option that lets the user set the number of outgroups (default to 2) without editing the XML (so `--maxOutputs` if defined overrides `<outgroup max_num_outgroups>` in the config.  
I think at some point I'd like to try implementing a more dynamic outgroup count (ie use more outgroups if they …

Interface for making outgroup selection sex-chromosome aware

---

src/cactus/progressive/cactus_progressive.py

Sigh, this breaking (on systems with > 10 cpus) assert snuck in via #1266

remove debug print/assert that was accidentally merged (and released)

---

build-tools/downloadMafTools
src/cactus/maf/cactus_hal2maf.py
src/cactus/maf/cactus_maf2bigmaf.py

This is my favourite type of bioinformatics.  We're pushing to use genbank accessions for genomes names in our alignments, ex `GCA_028858775.2`.  But since MAF stores both sequence and genome names in a single string, a convention is needed to separate them.  This convention is `.` meaning that tools relying on the convention which include `hgLoadMafSummary` and `mafDuplicateFilter` will completely (and silently) fall down on inputs where `.`s appear in the species names, producing incorrect output. 
This PR adds a step to `cactus-hal2maf / cactus-maf2bigmaf` to rename genomes to alphanumeric strings before doing any maf processing that might rely on naming convetions, then rename them back after.  
It also sorts maf rows in the output by their distance to the reference in the tree.  Note …

handle dots in genome names in maf processing

---

src/cactus/maf/cactus_hal2maf.py
src/cactus/paf/local_alignment.py
src/cactus/pipeline/cactus_workflow.py
src/cactus/progressive/cactus_progressive.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

It's frustrating when cactus calculates the memory required for a job, issues it, then that memory is too large for the batch system to run it, because it's a non-recoverable error.  And it could be that the estimate was a bit too conservative and the job could have been run after all (it's also possible that the estimate was fine and the job would end up crashing).  
This comes up in pangenome indexing (where `--indexMemory` already works like a type of global override), but also when dealing with very repetitive pariwise alignments.  
This PR introduces some logic to clamp memory estimates with a value from `--maxMemory`.   So if you are running on a cluster with at most 1TB available, you can run `--maxMemory 1TB` and cactus will never ask for anymore memory no matter what.  
Since …

use --maxMemory to clamp memory requirements of bigger jobs

---

build-tools/downloadMafTools
doc/progressive.md
src/cactus/cactus_progressive_config.xml
src/cactus/progressive/cactus_progressive.py
src/cactus/progressive/progressive_decomposition.py
src/cactus/shared/configWrapper.py
test/evolverTest.py

You used to be able to replace something like `((a,b)(c,d))` with `(a,b,c,d)` in an input tree.  It would lead to more memory usage, but might actually help coverage since two internal ancestors are avoided. 
But sometime over the past year, this seems to have changed. I just noticed that doing this caused a dramatic loss of coverage inside the subtree in question when aligning some apes.  
So now the best practice seems to be to always binarize the input tree, even if the choice of topology may not necessarily be clear.  This PR enforces this.  IF you pass in a tree with a node with `>2` children, it will fail with an error.  This check can be disabled in the configuration XML. Hopefully this will be fixed at some point.

Disable support for multi-way splits

---

src/cactus/progressive/cactus_progressive.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_pangenome.py
src/cactus/setup/cactus_align.py
src/cactus/shared/common.py

This is mostly for `cactus-pangenome` which, by chaining together a bunch of workflows, has plenty of opportunity to accumulate jobstore bloat.  This PR adds some following cleanup steps
* erase fasta and paf after consolidated (just paf in progressive mode due to outgroups)
* original fasta and minigraph output after `graphmap-split` 
* chromosome hal_ids after merging together
On the yeast graph, this drops peak usage from `1.1G` to `896G`.  I think it'll have more impact on big human graphs where sequence data accounts for a bigger proportion of disk usuage.

Explicitly erase some unneeded jobstore files

---

src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_progressive.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/shared/common.py

Looks like the preprocessor, which may run 4-5 steps on the input sequence, along with unzip them, will keep aorund every intermediate copy in the jobstore.  This PR, along the lines #1295, explicitly deletes the previous iteration once the new version is computed.

Clean out jobstore cruft in preprocessor

---

doc/progressive.md
src/cactus/blast/cactus_blast.py
src/cactus/cactus_progressive_config.xml
src/cactus/progressive/cactus_progressive.py
src/cactus/shared/configWrapper.py

Right now there's a crucial bit in the README about manually increasing the blast chunk size for cpu jobs:
>cp cactus-bin-v2.7.2/src/cactus/cactus_progressive_config.xml ./config-slurm.xml
>sed -i config-slurm.xml -e 's/blast chunkSize="30000000"/blast chunkSize="90000000"/g'
>sed -i config-slurm.xml -e 's/dechunkBatchSize="1000"/dechunkBatchSize="200"/g'
This brings down the number of jobs by a factor of 9, which helps to not spam the cluster with too many jobs (ie reduces from 100s of thousands to 10s of thousands).  I think slurm itself can handle big queues, but I was seeing some issues in early tests that may be related to the jobstore pushing the network filesystem with so many jobs.  
Anyway, this PR changes cactus so that is applied automatically, and controlled by …

auto-scale blast chunk size on slurm

---

src/cactus/shared/common.py

I hacked this logic (#1283, #1292) in when struggling with some T2T alignments on Slurm, but clearly didn't test it enough since it [completely broke](https://github.com/DataBiosphere/toil/issues/4773#issuecomment-1988752187) cactus on AWS/MESOS.  The reason is that it's using (and int-casting) `options.maxMemory` and `options.defaultMemory` from Toil, which default to `None` on AWS/MESOS (but not single machine and slurm where I was testing).   
Anyway, this PR should fix it, buy handling None values (and making sure that passed-in values are properly parsed).

Fix bug introdued with new memory environment variables

---

preprocessor/Makefile
preprocessor/cactus_filterRedBreakingSequences.c
preprocessor/cactus_redPrefilter.c
src/cactus/cactus_progressive_config.xml
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/redMasking.py

I tried to put a cactus ancestor through Red RepeatMasking via the cactus preprocessor and it crashed right away -- something I haven't seen on any real or test data so far.
After some trial and error, it looks like Red will crash if the input contains a contig that is 
* tiny. not sure the exact limit but 20kb seems to work on tests (though on real data it can mask much smaller sequences at least sometimes)
* or really low-information. for example, a contig that is just `N`'s will crash Red no matter how long it is.  
This PR adds a prefilter to catch these cases (it would eventually be nice to get into Red's code to fix it properly).  Contigs that are smaller than `20kb` or which are more than `98%` a single base are filtered out before `Red` then added back in after.  In the second …

Add Red prefilter

---

build-tools/downloadMafTools
doc/progressive.md
src/cactus/maf/cactus_hal2maf.py
test/evolverTest.py

This PR integrates some more `taffy` functionality, namely `taffy index` and `taffy coverage`, as optional postprocessing steps.
You can also output `.taf` and `.taf.gz` files by using the extension in the output filename.

Indexing, coverage stats and TAF output options for cactus-hal2maf

---

doc/running-in-aws.md

This is in response to #1322.  If you follow the current guide and clone master onto your head node, it won't necessarily work.  This is because you'll be running python from the master branch with binaries from the docker image for the latest release, and there can be conflicts between the versions.  Even if it does work, Cactus will have been run with a chimera of versions that make debugging and reproducing more complicated. 
This PR changes the document to suggest installing the latest release.

update aws doc to use cactus release

---

doc/pangenome.md
preprocessor/cactus_sanitizeFastaHeaders.c

`cactus-pangenome` will crash if any of the input fasta contigs have a suffix like `:10-100` denoting a subpath range (a fairly standard annotation that, ex, `samtools faidx` uses -- note it's 1-based end inclusive).   This seems to be because these types of subranges are already being used in GAF path steps coming out of minigraph, which confuses a parsing step in Cactus.  
Not related, but there is already logic to convert subranges to `_sub_9_100` (0-based exclusive end) going into pangenome HALs because the genome browser can't (couldn't?) handle `:` and/or `-`.  
This PR just bumps this existing logic forward, paths of the form `chr1:10-100` will get converted right away to `chr1_sub_9_100` in `cactus_sanitizeFastaHeaders` -- the end result being 1) the crash is fixed while 2) the …

Preprocess :start-end samtools-style path ranges in pangenome input

---

src/cactus/cactus_progressive_config.xml

abPOA has an option to speed up alignment by using a minimizer-based seeding strategy to find anchors.  But, in rare cases it can [crash or, more worryingly, output a completely incorrect result](https://github.com/yangao07/abPOA/issues/66)  -- which happens seems system-dependent.  
This PR turns it off by default in the configuration file.  I ran two tests with Cactus v.2.8.0 with seeding on and off.  `chr10` from the the chm13-based v1.1 HPRC pangenome, and `Anc08` (mouse/rat + outgroups) from the Zoonomia 10-way test.  
The `cactus_consolidated` running times are
```
Seed   Cons Time (s) BAR time (s) RAM (GB)
----------------------------------------------------
Anc08   Yes     36,543       20,478        406
Anc08   No      45,153       26,025        406
chr10   Yes     14,413 …
```

Turn abpoa seeding off by default

---

doc/progressive.md
src/cactus/maf/cactus_hal2maf.py
test/evolverTest.py

Add subrange support to `cactus-hal2maf` using `--refSequence --start --length`.  Multiple ranges can be specified with the options.  `--bedRanges` option also added to pass in the ranges as a file. 
I need this to debug the strand bug in #1320 which happens on big input. 
Also, resolves #1335.

add range support for cactus-hal2maf

---

doc/progressive.md
src/cactus/maf/cactus_maf2bigmaf.py

Bigmaf conversion is very sensitive to "." characters in genome names. `cactus-maf2bigmaf` hacks around this using genome names in the halfile.  But this logic doesn't work when running withpout the halfile.   Simplest fix seems to just make the hal file mandatory, which is what this PR does. 
Resolves #1332

deprecated cactus-maf2bigmaf --chromSizes

---

src/cactus/maf/cactus_hal2chains.py

Apparently the BigChain documentation https://genome.ucsc.edu/goldenPath/help/bigChain.html and https://genome.ucsc.edu/goldenPath/help/examples/bigChain.as is wrong about `chainScore` being a `uint`.  Which explains a lot, because `bedToBigBed` fails with an `integer overflowed, limit=4294967295 ...` whenever trying to produce any kind of chains at scale.  I'd previously hacked `cactus-hal2chains` to clamp this before bigBed conversion, but @diekhans has pointed me to the [official bigChain.as](https://raw.githubusercontent.com/ucscGenomeBrowser/kent/cb3cd0e9c5b9006b7d316df7905faa516f880c6b/src/hg/lib/bigChain.as) which uses a `double` so this PR removes the clamp and switches to using this version.

Use bigChain.as from kent src

---

Makefile
src/cactus/maf/cactus_hal2maf.py
test/evolverTest.py

Today I learned that `cactus-hal2maf --binariesMode docker` isn't covered by the automatic tests... with predictable results. 
This PR fixes the tests and `cactus-hal2maf` which has a recentish path-naming bug that stops it from working with docker binaries (but not inside docker images or with local binaries).
Resolves #1349

Fix cactus-hal2maf --binariesMode docker

---

.gitlab-ci.yml
Dockerfile
Makefile
README.md
build-tools/downloadPangenomeTools
doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

I've been wasting a lot of time lately by manually running vcf normalization commands.  This PR adds two normalization steps to the pipeline:
* `bcftools norm -f`: On by default, but can be toggled in the config XML
* `vcfwave`: Toggle on with `--vcfwave` (this will output an *additional* VCF that has bee n `vcfwave`-normalized in addition to the usual output)
Because I couldn't figure out how to make a static `vcfwave` binary, I'm only including it in the Docker release for now.  There's a hopefully-helpful error checker to help users work around this.

add vcfwave and bcftools norm

---

src/cactus/shared/common.py

Printing the "cpu not compatible with avx2" message whenever a command crashes with exit 4 can be confusing, as shown in #1348 .  
This PR requires "illegal instruction" to be found in stderr (if stderr captured) for the message to happen, which will hopefully make cases like #1348 more rare.

Try to make illegal instruction message more precise

---

doc/progressive.md
src/cactus/maf/cactus_hal2maf.py
src/cactus/maf/cactus_maf2bigmaf.py

`cactus-hal2maf` filters out gaps and unaligned regions automatically. I think this was originally done to better fit what the Genome Browser expects.  But at least a few people have been disappointed to not find their entire reference interval in the MAF whether or not it's aligned.  
So this PR takes this filter step out of `cactus-hal2maf` and, since it's browser-specific, moves it into `cactus-maf2bigmaf`
Resolves #1362

Move maxRefNFrac and minLines filters from hal2maf to maf2bigmaf

---

Makefile
src/cactus/preprocessor/cactus_preprocessor.py

I noticed this while trying to reproduce #1370.  
When I added the RED repeatmasker, the intention was to replace the lastz masker by default.  This is how `cactus` works, but `cactus-preprocess` still runs the lastz masker after Red.  
This PR fixes `cactus-preprocess` to just run Red by default.  It also fixes the `--maskMode` option so that it works as described (runs only the selected masker).

fix cactus-preprocess --maskMode option

---

src/cactus/progressive/cactus_progressive.py

The job `trim_unaligned_sequences` currently estimates its memory as a function of its input size.  
```
memory=cactus_clamp_memory(8*sum([seq.size for seq in sequences]) + 32*alignments.size))
```
This seems to have been working fairly well but @ph09 ran into an issue where it would estimate the minimum value of `2G` while needing roughly `11G`.  It turns out this happens at the root node of 3-human alignment, where the input PAF is `40Mb` but there are no input sequences.  This explains the minimal estimate.  But I guess `paffy to_bed` uses memory proportional to the ingroup sequences, then it runs out of memory.  
This PR changes the logic so that outgroup trimming is turned off when there are no outgroups.  From what I can tell looking at the code, it's not doing anything in these …

Only trim outgroups if there are any

---

src/cactus/maf/cactus_maf2bigmaf.py

Fixed mem_mult assignment type in the non .gz case

Fixed typo in cactus_maf2bigmaf.py

---

src/cactus/refmap/cactus_graphmap_join.py

#1402 brings up a good point about errors within this script not being handled properly.  The right thing to do is push this logic into Toil jobs rather than calling out to the bash script.  But in the meantime, this patch should hopefully prevent it from silently producing truncated output in the event of a crash.

catch errors in vcf-bubwave script

---

src/cactus/preprocessor/redMasking.py

As evidenced by #1408 I guess `awk` can return sums in scientific notation, at least on some systems.   This PR fixes the red-masking pipeline to handle this situation without crashing.   
Should resolve #1408

handle scientific notation awk result

---

Dockerfile.segalign
README.md
ReleaseNotes.md
build-tools/makeGpuDockerRelease
doc/progressive.md
setup.py
toil-requirement.txt

The GPU docker image builder script failed for [v2.8.3](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.8.3) at the very end when it verifies that `cactus --help` runs through
```
Traceback (most recent call last):
File "/cactus/venv-cactus/bin/cactus", line 5, in <module>
from cactus.progressive.cactus_progressive import main
File "/cactus/venv-cactus/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 20, in <module>
from toil.lib.bioio import getTempFile
File "/cactus/venv-cactus/lib/python3.8/site-packages/toil/lib/bioio.py", line 18, in <module>
from toil.test import get_temp_file
File "/cactus/venv-cactus/lib/python3.8/site-packages/toil/test/__init__.py", line 54, in <module>
from backports import zoneinfo
ModuleNotFoundError: No module …
```

Bump gpu docker to ubuntu 22 as Toil 7.0 seems to want Python version > 3.8

---

src/cactus/refmap/cactus_graphmap_join.py

`vg deconstruct` can apparently produce invalid vcfs (#1402 #1416).  This PR adds `bcftools stats` after every VCF is created, with the hope of catching any errors right away.  Hopefully I can get the data to fix `deconstruct` ASAP, but it's probably a good idea in general to spend a few minutes validating vcfs (it has been well worth it to add `vg validate` for all the various graphs that are created).  
The stats are also written to the output in `<vcf path>.stats`, which may be convenient for some 
*update* `view` seems better than `stats` at catching formatting errors in some cases, so switched to that instead. so no extra stats returned after all

use bcftools view to sanity check every vcf

---

build-tools/downloadPangenomeTools

This fixes an [issue](https://github.com/pangenome/pggb/issues/287) where `vcfbub` could write records that are invalid because they are missing genotype columns.  
Resolves #1416.

update vcfbub to v0.1.1

---

doc/pangenome.md
doc/sa_refgraph_hackathon_2023.md
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

Previously, you needed to run `--hapl --giraffe clip` to make the new haplotype subsampling index.  This is because the `.dist` index generated by `--giraffe` is a requirement for making the `.hapl` index. 
But making the `.dist` index of the clip graph in this way (as opposed to the filter graph) could take loads of time and memory.  And, I just found out, `vg haplotypes` doesn't actually need a full distance index: it can get by on a top-level index constructed with `vg index --snarl-limit 1`.  
For `hprc-v1.1-mc-chm13.dist`, the savings are substantial by using this option.
```
vg index hprc-v1.1-mc-chm13.xg -j top.dist --snarl-limit 1"
Elapsed (wall clock) time (h:mm:ss or m:ss): 57:22.61
Maximum resident set size (kbytes): 79057736
vg index hprc-v1.1-mc-chm13.xg -j default.dist" …
```

Use smaller distance index for --hapl, and decouple from --giraffe

---

src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_minigraph.py
test/evolverTest.py

Instead of running a single `minigraph -xggs` construction call on all input sequences at once, it now runs a sequence of such calls on smaller batches, each in a separate Toil job.
The reasons for doing this are:
* Each batch serves as a checkpoint for a possibly resuming a failed workflow from.  For example, when aligning 200 sequences, if you run out of memory on the last one, then you don't need to realign all 200, rather it will start again at 150 (using default batch size of 50).  
* Smaller command lines.  Cactus will sometimes use strings for parameter lists (as per its piping and docker etc logic).  If you have enough input genomes, then it's easy to overrun a system limit like `MAX_ARG_STRLEN` which prevents the `minigraph` command from being run altogether.  It also makes for …

Divide minigraph construction into chunks

---

src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

There are apparently some bugs in `vcfwave`: https://github.com/vcflib/vcflibissues/403 in that it can produce
* incorrect genotypes
* incorrect `AT` fields
Until they are fixed, I'm adding this quick patch that splits multallelic records and drops `AT` fields *before* `vcfwave` gets run.  This seems to fix the given examples, but I'm not sure if it resolves everything.  The splitting comes at the cost of variants `ID`s no longer being unique, but I think that's still preferred over wrong genotypes.

Split multiallelic sites and drop AT fields before running vcfwave

---

src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_refmap.py
src/cactus/setup/cactus_align.py

It seems that `compute_outgroups()` uses quadratic memory in the size of the tree, I guess for a big distance matrix.  This has never been an issue for progressive cactus, but as I'm testing making pangenomes with tons of small inputs it's now a bottleneck. 
This PR just disables outgroup computation for pangenomes (they aren't used at all anyway). But at some point it'd be good to revise things so that outgroup computation can work without the full matrix in memory...
Note, this means #1043 will need updating to add more nuanced control / a better fix.

disable outgroup computation for pangenomes

---

src/cactus/refmap/cactus_minigraph.py

They are run in a follow-on chain and Toil apparently handles them with recursive calls.  So having more than 999 results in a Python exception about a recursion limit being exceeded.  
The default batch size is 50.  This PR will boost it to whatever's needed (with a warning) to keep the number of jobs comfortably under 999, allowing inputs of more than 50k genomes to run through (this part of the pipeline) ok.

Cap number of minigraph construction batches

---

bar/impl/bar.c
bar/impl/poaBarAligner.c
bar/inc/poaBarAligner.h
bar/tests/poaBarTest.c
doc/sa_refgraph_hackathon_2023.md
src/cactus/cactus_progressive_config.xml
src/cactus/progressive/multiCactusTree.py
src/cactus/progressive/progressive_decomposition.py

This PR contains a couple more patches to allow pangenome alignments with tons of samples to go through.  
* Spanning tree calculation is used to fit outgroups into a subtree, and seems to be quadratic (like outgroup selection itself) in the number of species.  This PR disables this computation when it's not needed (which is the case for pangenomes).  
* abPOA's "progressive" mode is on by default.  It sorts input sequences using a distance matrix which is quadratic in input genome count as well, and therefore doesn't scale past about 10k.  This PR adds a limit in the config, `partialOrderAlignmentProgressiveMaxRows`, which defaults to `5000`, and makes sure progressive is disabled in abPOA for any inputs with more than this many rows.  I'm using `5000` even though it can go a bit higher …

Scaling improvements in Cactus alignment stage for high-depth pangenomes. 

---

preprocessor/cactus_sanitizeFastaHeaders.c

I was trying to reproduce the `lastz` failure from #1466 by adding a sequence like
```
>
ACACACACCAC
```
to the FASTA.  `lastz` seems to support this okay by inventing its own sequence name for it, but it crashes downstream in `consolidated`.  
Anyway, this patches the `fasta` checker to through an error right away in this case.  But I don't think helps at all with the original issue.

add check for empty fasta header

---

src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py

I added `bcftools norm -f` (left shifting) to the VCF export logic by default in [2.8.2](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.8.2).  This makes for more consistent variant representation, but can result in overlapping sites.  This apparently [upsets pangenie](#1460), for which I don't want to break support.  
So this PR backtracks on this, making `bcftools norm` off by default.  Someone wanting to run it can do so pretty easily themselves, or turn it back on in the configuration.  It's still on by default for output normalized by `vcfwave`.  
There's a `vcflib` tool called `vcfcreatemulti` that appears to merge overlapping variants.  I'm a bit reluctant to try running it by default now because I'm not sure what it does to tags and, crucially, I don't have a …

Turn vcf left-shifting off by default.

---

doc/pangenome.md
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

`cactus-pangenome` originally had two types of output
* `giraffe-specific`  (`.gbwt, .xg, .min, .dist`)  whose nodes were chopped to 1024bp 
*  everything else (`.gfa.gz, .vcf.gz, .vg, odgi`) that had no node length limit.
A translation was kept between the two in a `.trans` file, which was later built into the `.gbz` format when we switched to that.  
This was always confusing, as it was difficult to use `vg` to debug the `gfa` or `vcf` and sometimes `giraffe` would produce output in one coordinate system when you expected the other. 
Now that `.gbz` is becoming a more general (not just for `giraffe`) interchange format, and the `.dist` file (which shares the node length limit) is starting to replace the old snarl format, having unchopped files hanging around only gets more confusing. …

Turn node chopping on for all output by default

---

test/evolverTest.py

I somehow broke the `--collapse` option before the last release.  Promoting it to the yeast test (from the evolver primates) should help prevent this from happening in the future.

add --collapse to yeast test

---

build-tools/downloadPangenomeTools

`vg paths -n` (path normalization) is now a default part of minigraph-cactus.  but on certain graphs, it can take a really long time.  I'm still not sure why, but it's simple enough to patch by [switching to the older snarls api](https://github.com/vgteam/vg/pull/4421).  This PR updates cactus to use a vg version containing this patch.

switch to patched vg to fix paths -n

---

src/cactus/refmap/cactus_pangenome.py
src/cactus/shared/common.py

I ran into an invald PAF error (from `convertCoordinates()` in `cactus_consolidated`), where the start coordinate exceeded the sequence length.  After some digging, it turns out that the FASTA file passed into `cactus_consolidated` was missing the last `~75kb` or so.  This fasta file is created by the `cactus-graphmap-split` phase.  It's checkedpointed to disk with `toil.exportFile` and then read back with `toil.importFile` before going into consolidated.  The version checkedpointed to disk is fine, but the version in the jobstore going into the job itself is short.  As unlikely as it seems the only explanation I can think of is that the import somehow happened before the export finished.   
So this PR does two things, that may or may not help:
* explicitly close the outfile file handle …

Small hacks to maybe avoid potential pangenome race condition

---

bar/impl/bar.c
bar/impl/endAligner.c
bar/impl/poaBarAligner.c
bar/inc/poaBarAligner.h
bar/tests/poaBarTest.c
src/cactus/cactus_progressive_config.xml

It's been a couple of times where it seems that `abPOA`'s "progressive" input sorter (`-p`) which is on by default in cactus only makes things worse.  
Instead of giving up on it entirely (I'm sure I've seen it help before), progressive sorting is now only activated if the input sequences are all the same length.  The logic being that we prefer sorting by length, but there's nothing much to lose  trying progressive when there is no length signal.  
A threshold (defaulting to 5% in the config) is used to determine if the lengths are the same.

Only use abPOA's progressive mode if input lengths all (about) the same

---

pipeline/cactus_consolidated.c
preprocessor/cactus_sanitizeFastaHeaders.c
reference/impl/buildReference.c
src/cactus/preprocessor/checkUniqueHeaders.py

Flowers are sorted by decreasing size when doing the parallel loops in BAR and Reference phases so longer jobs get queued first.  But the size is measured by `flower_getCapNumber()` and on a small test of chrI of the yeast pangenome, the 3 jobs that stand out as longest running don't have the most caps.  But they do have the longest `flower_getTotalBaseLength()`.  
Granted, this isn't a ton to go on, but this PR tries switching up the sort to use base length instead of caps.  And because base length is more involved to compute, it's done in parallel.  
The idea being to use this branch to run a couple big tests to see if it helps with wall time for some big, parallel, jobs.  It's kind of a long shot, but runtime does seem to be bounded by a single long job for many cases, so anything to …

Sort flowers by total-base-length instead of cap-number for bar/ref

---

src/cactus/shared/common.py

`singularity exec` takes in the environment from the caller, which in turn takes its `TMPDIR` from `--workDir` etc.  But what's a valid directory outside the container, may not be, apparently, valid inside the container.  
This had evidently come up before, as there's code to reset `TMPDIR` to `.` for `cactus_consoldiated` invocations.  This PR applies this to any command run via `singularity`.   
I think this may be a safer, more general patch than #1517 which addresses the same issue but for `bcftools sort` in particular. 
This does *not* seem to be an issue with docker as `docker run` doesn't import the environment.

apply local TMPDIR redirect to all singularity commands

---

preprocessor/cactus_sanitizeFastaHeaders.c

There seem to be gremlins in Cactus causing invalid FASTA files.  In `cactus-pangenome`, this has manifested as slightly truncated files being imported into chromosome alignment jobs.  And in progressive Cactus, there are a couple issues, #1466 #1525, reporting corrupt FASTA chunks (missing newline?) going into `lastz`.  
I still don't know what the underlying problem is, though on the pangenome side it really looks like the corruption is happening at the filesystem level.  
This PR just adds some asserts to try to catch these errors a little earlier to (hopefully) make debugging if / when they come up again.  
* `cactus_sanitizeFastaHeaders` now checks the sequence in addition to headers and reports an error if a non-ACGTN character is found. 
* `faffy chunk` and `faffy extract` changed …

Add checks for invalid sequence characters when writing temporary FASTA files

---

BIN-INSTALL.md
build-tools/downloadPangenomeTools
build-tools/downloadVCFWave

If I'm installing the cactus binaries release on our cluster, `vcfwave` is not included because there's no static binary for it. 
This PR breaks `vcflib` compilation into its own script and adds it as an option to the `BIN-INSTALL` instructions.  This way, it's relatively easy to download the binary release, then add in `vcwave` (via local build) if desired, so the release can be used without going through docker...

add vcfwave installation as option to BIN-INSTALL instructions

---

build-tools/makeBinRelease

I updated BIN-INSTALL.md to mention how to add `vcfwave` to a binary installation, but the relevant script wasn't actually in the release -- this PR fixes that.

include downloadVCFWave script in binary release

---

build-tools/downloadVCFWave
src/cactus/refmap/cactus_graphmap_join.py

Pull in latest vcflib with fix for https://github.com/vcflib/vcflib/issues/403 
I was using multi-allelic splitting as kind of a workaround for this issue (output seemed less wrong on biallelics), but if the issue is resolved then this shouldn't be needed anymore so I've removed it.

update to patched vcfwave; let it work with multiallelics

---

src/cactus/shared/common.py

... because apparently `--defaultCores` will set it to a float.  
Resolves #1539

Make sure "cores" specification always int

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

The `--no-nested-distance` option was [recently added](https://github.com/vgteam/vg/pull/4466) to improve performance when making a top-level distance index (ie as required for `.hapl` construction).  This PR switches to using this instead of `--snarl-limit 1`.  Should help considerably for giant graphs where this step was a bottleneck.

Use faster distance index construction

---

src/cactus/refmap/cactus_graphmap_join.py

This made it into master because it doesn't always cause the tests to fail, but now it's causing unrelated PRs to sometimes fail tests.  
There's a patch in #1536, but making a separate PR to get it in right away.

fix toil dependency bug in recent vcf refactor

---

doc/pangenome.md
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

This option prints out a list of snarls (from `vg stats -r --snarl-sample <REF>`), sorted in decreasing size on reference path.  This is very useful for debugging because giant snarls are often a consequence of assembly and/or alignment problems and can cause downstream issues due to the graph complexity they introduce.

Add snarl-stats option

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

Updates to the [latest gfaffix](https://github.com/marschall-lab/GFAffix/releases/tag/0.2.0), which has many interesting improvements. Thanks @danydoerr!

update gfaffix to v0.2.0

---

src/cactus/refmap/cactus_graphmap_join.py

GFAffix supports reference-W-lines since version 0.2.0; the version also fixes the header issue, which is also now removed from the code

Adjust to new GFAffix

---

preprocessor/cactus_sanitizeFastaHeaders.c

Sometime recently I added a check for non-AGCTN bases in `cactus_santizeFastaHeaders`.  The logic was to catch corrupt FASTA files (somethjing that has happened in the middle of the pipeline apparently due to file corruption) as soon as possible.  
But some assemblies, notably GRCh38 (!) contain these characters, ex: 
```
samtools faidx GCA_000001405.15_GRCh38_no_alt_analysis_set.fna chr1:248752514-248752515
>chr1:248752514-248752515
MC
```
which amounts to a substantial regression in the pipeline.  Such bases used to end up in `N` by the time they reached the HAL, which is the behaviour we want to preserve.  
This PR changes `cactus_santizeFastaHeaders` to do the hardmasking itself (and abort if a non-iupac character is found).  This ensures that the sequences are treated the same at …

Don't fail when encountering IUPAC genenerate DNA base characters in fasta check

---

src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py
test/evolverTest.py

Internally, cactus uses `id=<genome>|` to uniquely prefix contig names with genome names.  This scheme is used in all sorts of places through both the pangenome and progressive pipelines. It's generally invisible to any user-facing output and seems to work well enough.  
But these sorts of names are present in the `minigraph` graph `.sv.gfa.gz` constructed as the first step of Minigraph-Cactus.  While this is an "intermediate" file in terms of the entire pipeline, many users still want to use it directly and will be stuck dealing with the internal cactus naming conventions.  Especially if we end up shipping "official" minigraph graphs made with Cactus as part of the HPRC...
I think the best thing going forward is to refactor Cactus to go from using `id=<name>|` to PanSN (`#`-separators), …

Serialize minigraph gfa with Pan-SN contig names

---

src/cactus/cactus_progressive_config.xml

`abpoa`'s progressive mode works pretty well (which orders in the input sequences by similarity), which is why it's on by default in cactus.  But it's known to fall down in highly repetitive regions.  To get around this, I hacked in a heuristic to use sequence size (instead of similarity) instead of progressive when there was a signal for it, but I think this was too heavy handed.  
This PR reverts the above change (the logic can be reactivated via the `partialOrderAlignmentProgressiveMaxLengthDiff` option in the config).  Instead it shrinks the k/w minimizer parameters used by abpoa's progressive mode.  By using more/smaller minimizers, it seems to be able to get a better signal out of low-complexity regions, leading to better results in the problem areas I've tested on..

use finer seeds instead of length-delta toggle for poa progressive

---

.gitmodules
Makefile
README.md
build-tools/downloadPangenomeTools
build-tools/downloadVCFWave
setup.py
src/cactus/cactus_progressive_config.xml
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

This adds @Han-Cao's [merge_duplicates.py](https://github.com/Han-Cao/collapse-bubble/blob/master/scripts/merge_duplicates.py) as a post-processing step after `bcftools norm -f`.  
It merges together records at the same position that `bcftools norm` can create (see the original issue, #1493, for details). 
Unfortunately, it seems like `bcftools norm` can shift together sites that can't be represented as one without allele conflicts.  So the `--keep first` heuristic is used by default to choose one, but can be toggled in the `mergeDuplicatesOptions` field on the config XML. 
As it stands `bcftools norm -f` and `merge_duplicates.py` are both on by default for `vcfwave` output.  To apply it to the "Default" vcfs, then `bcftoolsNorm="1"` needs to be activated in the config. 
Stacks on #1491

Merge VCF records at the same position together after bcftools norm left shifts them

---

src/cactus/cactus_progressive_config.xml
src/cactus/progressive/seqFile.py
src/cactus/refmap/cactus_minigraph.py

Previously, genomes passed in via the `--reference` option would be added to minigraph first (and in the order they are passed), while remaining genomes would be added in decreasing order of their mash distance to the first reference. 
This PR changes it so that references 2...N are sorted with mash along with everything else.  
While the first genome passed with `--reference` must always be first, the order of the remaining genomes can be controlled with: 
* `minigraphSortInput="0"` use the ordering from the input file or
* [new] `minigraphSortReference="0"` use the ordering from the input file only for reference genomes.  
So for example, if I pass `--reference CHM13 GRCh38 GRCh37` and want to force `GRCh38` and `GRCh37` to be last, I would make sure they are at the end of the input …

Revise mash ordering for minigraph construct

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py
test/evolverTest.py

Apparently gfaffix 0.2 is [fixed](https://github.com/marschall-lab/GFAffix/issues/16#issuecomment-2660752267), so this PR changes cactus back to using it.  Thanks @danydoerr!
This reverts commit 6f43679136b6896d08df90232241835a72f78241.

Reapply "update gfaffix to v0.2.0"

---

src/cactus/refmap/cactus_graphmap_join.py

This is a fairly obscure bug that caught me off guard: If you run `cactus-pangenome` with `--reference GRCh38 CHM13`, then reproduce the indexes with `cactus-graphmap-join --reference GRCh38` it will actually leave `CHM13` as a reference path.  This PR changes it to allow the override.

allow graphmap-join to remove secondary reference

---

doc/pangenome.md
src/cactus/refmap/cactus_graphmap_join.py

While it'd be nice to get this working eventually, for now there are no guarantees that graphs constructed with `--collapse` satisfy the conditions (ie one top-level chain) that `vg haplotypes` needs to run.  So this PR forbids the two from being used together so as not to waste anyone's time (#1603) with cryptic errors.  Resolves #1603
On second thought, going to keep allowing `--collapse` with `--haplo`, since `--collapse` is an experimental option and the combination often works.  This PR now downgrades any failures of `vg haplotypes` to warnings when the `--collapse` option is used.

Forbid --haplo with --collapse

---

src/cactus/refmap/cactus_graphmap_join.py

Not sure what happened, but the output file of `--snarl-stats` stopped being a valid gzip file.  This PR should fix that.
resolves #1630

fix --snarlStats option

---

build-tools/downloadMafTools
build-tools/downloadPangenomeTools

Apparently when you untar something as root, the user and group ids in the archived files are kept.  In the tarball that `mash` comes from, these IDs happen to be unusually large, that apparently leads to some issues with the released Docker images.  
This PR adds the `--no-same-owner` flag to tar commands, which discards the original ids (as done when running `tar` as a non-root user. 
Resolves #1531

Don't keep original user ids when untarring (as root, in docker)

---

build-tools/downloadPangenomeTools
src/cactus/refmap/cactus_graphmap_join.py

Sigh.. this reverts commit 5cc60204ff075cdc540ff7edc7984a8fa65a90e0.
See https://github.com/marschall-lab/GFAffix/issues/17

Revert "Reapply "update gfaffix to v0.2.0""

---

src/cactus/blast/cactus_blast.py
src/cactus/maf/cactus_hal2chains.py
src/cactus/maf/cactus_hal2maf.py
src/cactus/maf/cactus_maf2bigmaf.py
src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/progressive/cactus_prepare.py
src/cactus/progressive/cactus_progressive.py
src/cactus/refmap/cactus_graphmap.py
src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_graphmap_split.py
src/cactus/refmap/cactus_minigraph.py
src/cactus/refmap/cactus_pangenome.py
src/cactus/refmap/cactus_refmap.py
src/cactus/setup/cactus_align.py

This came up here: https://github.com/DataBiosphere/toil/pull/5233#issuecomment-2718592241
Where apparently 
```
parser = ArgumentParser()
Job.Runner.addToilOptions(parser)
```
had been deprecated in favour of
```
parser = parser_with_common_options()
```
with one difference being how environment variables are handled.

switch to newer toil argparse interface

---

BIN-INSTALL.md
ReleaseNotes.md
doc/progressive.md
setup.py
src/cactus/shared/common.py

I'm pushing this out so soon after v2.9.4 because the slurm partition update is pretty significant.  And I need the gfaffix rollback/patch in a release asap so I can index some candidate hprc graphs asap with a release version of cactus.

prep release v2.9.5

---

BIN-INSTALL.md
ReleaseNotes.md
doc/progressive.md
setup.py
src/cactus/shared/common.py

I rushed [2.9.6](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.9.6) too much and it contains some bugs:
* `vcf`-pipeline crashed at `vcfwave` stage for grch38-based hprc graphs on chrEBV contig
* chromosome graph files got wrong names (ie chr1 might be in chr19.vg etc) -- really dumb bug introduced for no good reason in previous release.
Both these sadly necessitate another release....

prep release v2.9.7

---

doc/progressive.md
src/cactus/setup/cactus_align.py

I'm not sure why it was ever there, and it can cause problems when trying to run `cactus-align` in gpu environments. 
Also, add little blurb about the Cactus Snakemake at https://github.com/harvardinformatics/cactus-snakemake
Note: both these things arose in #1652

Remove --gpu option from cactus-align

---

src/cactus/paf/local_alignment.py
src/cactus/preprocessor/checkUniqueHeaders.py
src/cactus/refmap/cactus_refmap.py

faffy chunk can use about a chunk size's worth of memory, which is a problem when using giant chunk sizes (ex for gpu) on slurm.  this pr fixes it so toil asks for a bit more than the chunk size in memory.

specify memory for faffy chunk

---

api/tests/cactusParamsTest.c
src/cactus/cactus_progressive_config.xml
src/cactus/paf/local_alignment.py

`lastz` operates by looking up seeds then performing a series of extension and refinement steps.  In the case of of highly repetitive sequences, this process can potentially find millions of alignments.  This can 1) bog down Cactus by over-collapsing the sequence graph and, in extreme cases, 2) cause `lastz` itself to run for too long.
Normally we expect masking the input with RepeatMasker and subsequently in Cactus, Red, to work around these issues, but exceptions do arise (#1662).  
This is a quick patch to try to increase robustness by telling lastz to give up on a match after its gapless extension (HSP) phase if more that 100000 matches are found.  This seems to be, roughly, the highest number that can be used on the example from #1662 without a huge hit to runtime.  
I'll need to run …

use queryhsplimit to avoid super-long lastz runs

---

src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py
src/cactus/shared/configWrapper.py

lastz-based preprocessing has been disabled by default for a while now in favour of RED, since RED is so much faster.
gpu-based lastz processing, efficient when it worked but not especially stable, is especially deprecated now that SegAlign has been replaced by KegAlign, with the latter not having the specialized preprocessor script.  
This means that even in the GPU-enabled cactus docker image where all gpu flags are on by default in the config, there's no reason to fail if no GPUs are detected when running `cactus-preprocess`.  
This PR changes the GPU check (`initGPU()`) to only be run if the user has manually updated the config to force lastz preprocessing (not recommonded).  
Resolves #1652

Ignore gpu options in cactus-preprocessor unless lastz enabled

---

src/cactus/progressive/cactus_prepare.py
src/cactus/update/cactus_update_prepare.py

Should resolve https://github.com/ComparativeGenomicsToolkit/hal/issues/319
Also removes deprecated/incorrect `--realtimeLogging` option which appears by default.
Also: adds `--lastzCores` option to `cactus-prepare` as it's now essential for slurm-based gpu workflows.

Fix cactus-update-prepare replace to give the correct halRemoveGenomes command

---

src/cactus/preprocessor/cactus_preprocessor.py
src/cactus/shared/common.py

Resolves #1690
* `cactus-preprocess` corrected to run `importSingularityImage(options)`
* singularity image creation bug fixed to pull in the `-gpu` image when option specified

fix singularity init bugs with preprocess and gpu

---

preprocessor/cactus_sanitizeFastaHeaders.c

`cactus_sanitizeFastaHeaders` gets run at the outset of most cactus tools.  In addition to adding header prefixes etc, it detects various formatting issuesf in FASTA files that may cause downstream issues, such as empty or duplicate sequences and invalid characters.  
But apparently it will work just fine on completely empty files (see #1693).  Completely empty inputs will eventually lead to crashes in `cactus_consolidated`, and until then cause massive under-alignment.  What's worse, is that the pipeline will continue to run as normal before eventually failing, potentially wasting tons of time. 
I don't think there's a use case for empty sequence, so this PR modifies `cactus_sanitizeFastaHeaders` to abort with an error as soon as one is seen.

Fatal error as soon as empty input FASTA detected

---

.gitlab-ci.yml

See https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/92792 :+1: 
```
File "/builds/comparativegenomicstoolkit/cactus/venv/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_join.py", line 63, in <module>
import pysam
File "/builds/comparativegenomicstoolkit/cactus/venv/lib/python3.9/site-packages/pysam/__init__.py", line 21, in <module>
from pysam.libcalignedsegment import *
AttributeError: module 'pysam.libcalignedsegment' has no attribute 'CMATCH'
```

try downgrading pysam to get around weird import errors in ci

---

doc/cactus-update-prepare.md
src/cactus/update/cactus_update_prepare.py

This PR has edits to `cactus_update_prepare.py` that allow the new genome to have a new name in **replace** mode. See #1727 for background.
In this version, the genome to replace is parsed from the command line option `--genome` and the new name is retrieved from the first column of the input file (_e.g._ `./input.txt` from the example in the [docs](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/cactus-update-prepare.md)).
1. Built from source following instructions [here](https://github.com/ComparativeGenomicsToolkit/cactus/tree/3ac246f5afcdb1778079d2c4a2952a2f0c4662b6?tab=readme-ov-file#compiling-binaries-locally)
2. Ran from virtual env following instructions [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/3ac246f5afcdb1778079d2c4a2952a2f0c4662b6/B …

Update prepare replace name

---

src/cactus/cactus_progressive_config.xml
src/cactus/progressive/progressive_decomposition.py
src/cactus/shared/configWrapper.py

This PR fixes the "greedyLeaevs" toggle in the config, which wasn't working.   It also adds the "greedyLeavesPreference" option which does the `greedyLeaves`, but will prioritieze starred lines in the seqfile.  And, finally, it makes this the new default.  Even though the leaf outgroups will tend to be further away from the event, we still expect them to perform better than ancestors.

fix outgroup parameter; change default to greedy leaves/preference

---

doc/progressive.md
src/cactus/maf/cactus_hal2maf.py
test/evolverTest.py

I often find myself releasing two MAFs alongside Cactus alignments:
1. MAF file with paralogies (multiple rows from the same sample), normalized with `taffy`
2. Single-copy MAF, created from above with `mafDuplicateFilter -k`. 
This process is annoying, especially for huge files, since it involves either two calls to `cactus-hal2maf` (once with `--dupeMode single` and once without.  Or, more efficiently, creating thing first with `cactus-hal2maf`, then the second with `mafDuplicateFilter` directly.  
The goal of this PR is two modify `cactus-hal2maf` to be able to produce both of these outputs in the same run.  To do this I ended up generalizing the `--dupeMode` option into `--outType`, with the latter being able to accept multupe values.  
Old: 
`--raw`
`--dupeMode {single ancestral …

rejig cactus-hal2maf output interface

---

src/cactus/cactus_progressive_config.xml
src/cactus/paf/local_alignment.py

While fastga went through with the smaller ancestors on my 5-mammal test, it died right away when trying some birds in another test.  This PR
* adds a filter (fastga_minlength, default=500k) to the config xml that prevents sequences smaller than this value from getting aligned by FastGA
* fixes the lastz fallback to not exclude sequences that were completely unaligned by FastGA (from the above filter or because they are otherwise unalignable).
While I'm at it, I also added this logic to the normal outgroup aligning business: If a contig wasn't aligned at all to any ingroup (as unlikely as it is), it will now be aligned to outgroups instead of being (as far as I can tell) forgotten.

FastGA Fixes

---

src/cactus/refmap/cactus_graphmap_join.py
src/cactus/refmap/cactus_pangenome.py

Not sure how this snuck in there, but the minigraph merging was only happening properly in the step-by-step interface, and not with `cactus-pangenome`.  This PR fixes it.

fix .sv.gfa.gz output with cactus-pangenome --mgSplit
